export interface ExerciseEntry {
  id: string;
  name: string;
  muscleGroup: string[];
  equipment: string[];
  movementPattern: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  instructions: string[];
  commonMistakes: string[];
  alternatives: string[];
}

export const EXERCISE_DATABASE: ExerciseEntry[] = [
  // ── BARBELL ─────────────────────────────────────────────────────────────────
  {
    id: "bb-squat",
    name: "Barbell Back Squat",
    muscleGroup: ["quads", "glutes", "hamstrings", "core"],
    equipment: ["barbell"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Bar on upper traps, feet shoulder-width apart, toes slightly out.",
      "Brace core, take a deep breath, break at hips and knees simultaneously.",
      "Descend until thighs are at least parallel to the floor.",
      "Drive through the floor, keep chest tall on the way up.",
    ],
    commonMistakes: ["Knees caving in", "Heels rising", "Butt wink at the bottom", "Forward lean"],
    alternatives: ["bb-front-squat", "db-goblet-squat", "leg-press"],
  },
  {
    id: "bb-deadlift",
    name: "Barbell Deadlift",
    muscleGroup: ["hamstrings", "glutes", "back", "traps", "core"],
    equipment: ["barbell"],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Bar over mid-foot, hip-width stance, grip just outside legs.",
      "Hinge at hips, flatten back, lats tight before the pull.",
      "Push floor away, keep bar dragging up shins and thighs.",
      "Lock out hips at top — don't hyperextend.",
    ],
    commonMistakes: ["Rounding lower back", "Bar drifting away from body", "Jerking the bar"],
    alternatives: ["bb-sumo-deadlift", "db-rdl", "trap-bar-deadlift"],
  },
  {
    id: "bb-bench",
    name: "Barbell Bench Press",
    muscleGroup: ["chest", "triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Lie flat, eyes under bar, grip slightly wider than shoulder-width.",
      "Retract shoulder blades, arch slightly, feet flat on floor.",
      "Lower bar to lower chest with elbows at ~75° from torso.",
      "Press up and slightly back toward your face at lockout.",
    ],
    commonMistakes: ["Flaring elbows", "Bouncing bar off chest", "Losing leg drive"],
    alternatives: ["db-press", "incline-bb-bench", "chest-fly-machine"],
  },
  {
    id: "bb-ohp",
    name: "Barbell Overhead Press",
    muscleGroup: ["shoulders", "triceps", "core", "upper chest"],
    equipment: ["barbell"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Grip just outside shoulders, bar resting on front delts.",
      "Brace hard, press bar straight up clearing chin.",
      "At top, push head through so bar is over the traps.",
      "Lower controlled to starting position.",
    ],
    commonMistakes: ["Excessive lower back arch", "Bar path too far forward", "Not locking out"],
    alternatives: ["db-shoulder-press", "machine-shoulder-press", "push-press"],
  },
  {
    id: "bb-row",
    name: "Barbell Bent-Over Row",
    muscleGroup: ["back", "biceps", "rear delts"],
    equipment: ["barbell"],
    movementPattern: "pull",
    difficulty: "intermediate",
    instructions: [
      "Hip hinge to ~45°, overhand grip shoulder-width.",
      "Pull bar to lower sternum, lead with elbows.",
      "Squeeze lats at top, lower controlled.",
    ],
    commonMistakes: ["Rounding back", "Using momentum", "Pulling to wrong point"],
    alternatives: ["db-row", "cable-row", "seated-row-machine"],
  },
  {
    id: "bb-rdl",
    name: "Barbell Romanian Deadlift",
    muscleGroup: ["hamstrings", "glutes", "lower back"],
    equipment: ["barbell"],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Stand tall, overhand grip at hip-width.",
      "Push hips back keeping bar close to legs, slight knee bend.",
      "Lower until you feel a strong hamstring stretch (mid-shin level).",
      "Drive hips forward to stand, squeeze glutes at top.",
    ],
    commonMistakes: ["Rounding back", "Bending knees too much", "Bar drifting forward"],
    alternatives: ["db-rdl", "good-morning", "cable-pull-through"],
  },
  {
    id: "bb-hip-thrust",
    name: "Barbell Hip Thrust",
    muscleGroup: ["glutes", "hamstrings"],
    equipment: ["barbell", "bench"],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Upper back on bench, bar over hip crease with pad.",
      "Feet flat on floor, drive hips up to full extension.",
      "Squeeze glutes hard at top, hold 1 second.",
      "Lower controlled to just above ground.",
    ],
    commonMistakes: ["Hyperextending lower back", "Feet too close or far", "Not reaching full extension"],
    alternatives: ["bw-glute-bridge", "cable-pull-through", "db-rdl"],
  },
  {
    id: "bb-front-squat",
    name: "Barbell Front Squat",
    muscleGroup: ["quads", "core", "glutes"],
    equipment: ["barbell"],
    movementPattern: "squat",
    difficulty: "advanced",
    instructions: [
      "Bar on front delts, elbows high and parallel to floor.",
      "Upright torso throughout — this is the key cue.",
      "Squat deep keeping elbows up the whole time.",
      "Drive up keeping chest tall.",
    ],
    commonMistakes: ["Elbows dropping", "Forward torso lean", "Wrists bending back"],
    alternatives: ["bb-squat", "db-goblet-squat", "hack-squat"],
  },
  {
    id: "bb-sumo-deadlift",
    name: "Sumo Deadlift",
    muscleGroup: ["glutes", "adductors", "hamstrings", "back"],
    equipment: ["barbell"],
    movementPattern: "hinge",
    difficulty: "advanced",
    instructions: [
      "Wide stance, toes pointing out, grip inside legs.",
      "Chest tall, push knees out toward toes before pulling.",
      "Bar stays close to legs, drive hips through at lockout.",
    ],
    commonMistakes: ["Knees caving in", "Hips rising before bar", "Not pushing knees out"],
    alternatives: ["bb-deadlift", "leg-press", "db-rdl"],
  },
  {
    id: "incline-bb-bench",
    name: "Incline Barbell Bench Press",
    muscleGroup: ["upper chest", "shoulders", "triceps"],
    equipment: ["barbell", "bench"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Bench at 30-45°, grip just wider than shoulder-width.",
      "Lower to upper chest, elbows at 60-75°.",
      "Press up and slightly back to lockout.",
    ],
    commonMistakes: ["Too steep incline (shoulder dominant)", "Flaring elbows", "Partial reps"],
    alternatives: ["incline-db-press", "bb-bench", "cable-fly"],
  },

  // ── DUMBBELL ─────────────────────────────────────────────────────────────────
  {
    id: "db-goblet-squat",
    name: "Dumbbell Goblet Squat",
    muscleGroup: ["quads", "glutes", "core"],
    equipment: ["dumbbell"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Hold dumbbell vertically at chest, feet shoulder-width, toes out.",
      "Squat deep keeping chest tall and elbows inside knees.",
      "Drive through heels to stand.",
    ],
    commonMistakes: ["Heels rising", "Elbows hitting knees", "Rounding back"],
    alternatives: ["bb-squat", "bb-front-squat", "bw-squat"],
  },
  {
    id: "db-press",
    name: "Dumbbell Bench Press",
    muscleGroup: ["chest", "triceps", "shoulders"],
    equipment: ["dumbbell", "bench"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Lie flat, dumbbells at chest level, neutral grip.",
      "Press up, slight arc toward center at top.",
      "Lower until elbows are slightly below bench level.",
    ],
    commonMistakes: ["Flaring elbows", "Uneven pressing", "Not touching full range"],
    alternatives: ["bb-bench", "push-up", "chest-fly-machine"],
  },
  {
    id: "db-row",
    name: "Dumbbell Single-Arm Row",
    muscleGroup: ["back", "biceps", "rear delts"],
    equipment: ["dumbbell", "bench"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Knee and hand on bench, opposite foot on floor.",
      "Pull dumbbell to hip, elbow close to body.",
      "Squeeze lat at top, lower fully.",
    ],
    commonMistakes: ["Rotating torso", "Short range of motion", "Pulling with bicep only"],
    alternatives: ["bb-row", "cable-row", "seated-row-machine"],
  },
  {
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    muscleGroup: ["shoulders", "triceps"],
    equipment: ["dumbbell"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Seated or standing, dumbbells at ear level, palms forward.",
      "Press straight up, slight arc to meet at top.",
      "Lower controlled to start position.",
    ],
    commonMistakes: ["Leaning back excessively", "Wrists bending", "Partial range"],
    alternatives: ["bb-ohp", "machine-shoulder-press", "pike-push-up"],
  },
  {
    id: "db-curl",
    name: "Dumbbell Bicep Curl",
    muscleGroup: ["biceps", "forearms"],
    equipment: ["dumbbell"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Stand with dumbbells at sides, palms forward.",
      "Curl up keeping elbows fixed at sides.",
      "Squeeze bicep at top, lower fully.",
    ],
    commonMistakes: ["Swinging body", "Elbows drifting forward", "Not lowering fully"],
    alternatives: ["cable-curl", "hammer-curl", "barbell-curl"],
  },
  {
    id: "db-tricep-ext",
    name: "Dumbbell Overhead Tricep Extension",
    muscleGroup: ["triceps"],
    equipment: ["dumbbell"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Hold one dumbbell overhead with both hands, elbows by ears.",
      "Lower behind head by bending elbows.",
      "Extend fully at top.",
    ],
    commonMistakes: ["Elbows flaring out", "Short range of motion", "Arching back"],
    alternatives: ["cable-tricep-pushdown", "dip", "skull-crusher"],
  },
  {
    id: "db-lunge",
    name: "Dumbbell Lunge",
    muscleGroup: ["quads", "glutes", "hamstrings"],
    equipment: ["dumbbell"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Dumbbells at sides, step forward into a lunge.",
      "Back knee almost touches floor, front knee over ankle.",
      "Push off front foot to return.",
    ],
    commonMistakes: ["Front knee caving in", "Leaning too far forward", "Short stride"],
    alternatives: ["bw-lunge", "split-squat", "leg-press"],
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian Deadlift",
    muscleGroup: ["hamstrings", "glutes", "lower back"],
    equipment: ["dumbbell"],
    movementPattern: "hinge",
    difficulty: "beginner",
    instructions: [
      "Dumbbells in front of thighs, push hips back.",
      "Lower dumbbells close to legs until hamstring stretch.",
      "Drive hips forward to stand.",
    ],
    commonMistakes: ["Rounding back", "Bending knees too much", "Looking up straining neck"],
    alternatives: ["bb-rdl", "good-morning", "bw-glute-bridge"],
  },
  {
    id: "db-lateral-raise",
    name: "Dumbbell Lateral Raise",
    muscleGroup: ["shoulders", "side delts"],
    equipment: ["dumbbell"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Light dumbbells at sides, slight forward lean.",
      "Raise arms to shoulder height, slight elbow bend.",
      "Lead with pinky, pause at top, lower slow.",
    ],
    commonMistakes: ["Too heavy (shrugging)", "Swinging for momentum", "Going above shoulder height"],
    alternatives: ["cable-lateral-raise", "machine-lateral-raise", "face-pull"],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    muscleGroup: ["upper chest", "shoulders", "triceps"],
    equipment: ["dumbbell", "bench"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Bench at 30-45°, dumbbells at chest, neutral or pronated grip.",
      "Press up and slightly in, controlled arc.",
      "Lower to chest level, elbows at 75°.",
    ],
    commonMistakes: ["Incline too steep", "Flaring elbows", "Dropping dumbbells fast"],
    alternatives: ["incline-bb-bench", "cable-fly", "bb-bench"],
  },

  // ── BODYWEIGHT ───────────────────────────────────────────────────────────────
  {
    id: "push-up",
    name: "Push-Up",
    muscleGroup: ["chest", "triceps", "shoulders", "core"],
    equipment: ["bodyweight"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Hands slightly wider than shoulders, body in a straight line.",
      "Lower chest to floor, elbows at ~45° from torso.",
      "Push back up fully, keep core tight throughout.",
    ],
    commonMistakes: ["Sagging hips", "Flaring elbows", "Partial range"],
    alternatives: ["db-press", "bb-bench", "chest-fly-machine"],
  },
  {
    id: "pull-up",
    name: "Pull-Up",
    muscleGroup: ["back", "biceps", "core"],
    equipment: ["pull-up bar"],
    movementPattern: "pull",
    difficulty: "intermediate",
    instructions: [
      "Overhand grip wider than shoulders, hang fully.",
      "Drive elbows down and back to pull chest to bar.",
      "Lower fully with control.",
    ],
    commonMistakes: ["Kipping (unless intended)", "Partial range", "Not depressing scapula first"],
    alternatives: ["lat-pulldown", "assisted-pull-up", "cable-row"],
  },
  {
    id: "dip",
    name: "Tricep Dip",
    muscleGroup: ["triceps", "chest", "shoulders"],
    equipment: ["bodyweight", "dip bars"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Grip parallel bars, arms straight, slight forward lean for chest focus.",
      "Lower until elbows at 90°, keep controlled.",
      "Press up to full extension.",
    ],
    commonMistakes: ["Shrugging shoulders", "Too wide a dip", "Swinging legs"],
    alternatives: ["push-up", "db-tricep-ext", "cable-tricep-pushdown"],
  },
  {
    id: "bw-squat",
    name: "Bodyweight Squat",
    muscleGroup: ["quads", "glutes", "hamstrings"],
    equipment: ["bodyweight"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Feet shoulder-width, arms out for balance.",
      "Sit back and down, keeping chest tall.",
      "Drive through heels to stand.",
    ],
    commonMistakes: ["Knees caving in", "Heels rising", "Shallow depth"],
    alternatives: ["db-goblet-squat", "bb-squat", "leg-press"],
  },
  {
    id: "bw-lunge",
    name: "Bodyweight Lunge",
    muscleGroup: ["quads", "glutes", "hamstrings"],
    equipment: ["bodyweight"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Step forward, lower back knee toward ground.",
      "Front knee tracks over foot, torso upright.",
      "Push back to start.",
    ],
    commonMistakes: ["Knee caving in", "Torso leaning forward", "Too narrow step"],
    alternatives: ["db-lunge", "split-squat", "step-up"],
  },
  {
    id: "bw-glute-bridge",
    name: "Glute Bridge",
    muscleGroup: ["glutes", "hamstrings"],
    equipment: ["bodyweight"],
    movementPattern: "hinge",
    difficulty: "beginner",
    instructions: [
      "Lie on back, knees bent, feet flat.",
      "Drive hips up squeezing glutes hard at top.",
      "Hold 1-2 seconds, lower controlled.",
    ],
    commonMistakes: ["Not squeezing glutes at top", "Feet too close", "Hyperextending back"],
    alternatives: ["bb-hip-thrust", "db-rdl", "bw-squat"],
  },
  {
    id: "plank",
    name: "Plank",
    muscleGroup: ["core", "shoulders", "glutes"],
    equipment: ["bodyweight"],
    movementPattern: "carry",
    difficulty: "beginner",
    instructions: [
      "Forearms on floor, elbows under shoulders, body in straight line.",
      "Squeeze glutes and abs, don't let hips sag or rise.",
      "Hold for prescribed time, breathe steadily.",
    ],
    commonMistakes: ["Hips sagging", "Hips piking up", "Holding breath"],
    alternatives: ["hollow-body-hold", "ab-wheel-rollout", "dead-bug"],
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscleGroup: ["core", "hip flexors", "shoulders"],
    equipment: ["bodyweight"],
    movementPattern: "rotate",
    difficulty: "beginner",
    instructions: [
      "High plank position, hands under shoulders.",
      "Drive knees to chest alternately in a running motion.",
      "Keep hips level, core tight throughout.",
    ],
    commonMistakes: ["Hips rising and falling", "Slow tempo with bad form", "Arms bending"],
    alternatives: ["plank", "burpee", "ab-wheel-rollout"],
  },
  {
    id: "burpee",
    name: "Burpee",
    muscleGroup: ["full body", "cardio"],
    equipment: ["bodyweight"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Stand, jump down to plank, perform a push-up.",
      "Jump feet to hands, explosive jump up with arms overhead.",
      "Land soft, repeat.",
    ],
    commonMistakes: ["Skipping push-up", "Landing stiff-legged", "Rushing and losing form"],
    alternatives: ["mountain-climber", "jump-squat", "bw-squat"],
  },
  {
    id: "box-jump",
    name: "Box Jump",
    muscleGroup: ["quads", "glutes", "calves", "cardio"],
    equipment: ["bodyweight", "box"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Stand facing box, quarter squat, swing arms.",
      "Explode up landing softly with both feet on box, knees bent.",
      "Stand fully, step down (don't jump down).",
    ],
    commonMistakes: ["Landing with straight legs", "Jumping down (injury risk)", "Too tall a box"],
    alternatives: ["jump-squat", "step-up", "broad-jump"],
  },
  {
    id: "jump-squat",
    name: "Jump Squat",
    muscleGroup: ["quads", "glutes", "calves"],
    equipment: ["bodyweight"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Squat to parallel, explode up off the ground.",
      "Land soft with knees bent, absorb impact.",
      "Immediately drop into next squat.",
    ],
    commonMistakes: ["Landing stiff", "Shallow squat", "Forward lean"],
    alternatives: ["box-jump", "bw-squat", "db-goblet-squat"],
  },
  {
    id: "split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: ["quads", "glutes", "hamstrings"],
    equipment: ["bodyweight", "bench"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Rear foot on bench, front foot out front.",
      "Lower back knee toward ground, front knee over foot.",
      "Drive through front heel to stand.",
    ],
    commonMistakes: ["Front knee caving", "Torso too upright or forward", "Foot too close"],
    alternatives: ["db-lunge", "bw-lunge", "step-up"],
  },

  // ── CABLE ────────────────────────────────────────────────────────────────────
  {
    id: "cable-row",
    name: "Cable Seated Row",
    muscleGroup: ["back", "biceps", "rear delts"],
    equipment: ["cable"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Sit at cable station, neutral grip handle.",
      "Pull to lower sternum keeping torso upright.",
      "Squeeze shoulder blades, control the return.",
    ],
    commonMistakes: ["Leaning back too much", "Rounding back", "Shrugging"],
    alternatives: ["db-row", "bb-row", "seated-row-machine"],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: ["back", "biceps"],
    equipment: ["cable"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Wide overhand grip, lean back slightly.",
      "Pull bar to upper chest, drive elbows down and back.",
      "Fully extend arms on the way up.",
    ],
    commonMistakes: ["Pulling to wrong position", "Swinging", "Not fully extending"],
    alternatives: ["pull-up", "db-row", "cable-row"],
  },
  {
    id: "cable-fly",
    name: "Cable Chest Fly",
    muscleGroup: ["chest", "front delts"],
    equipment: ["cable"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Cables at shoulder height, step forward in a staggered stance.",
      "Slight elbow bend, arc arms together in front of chest.",
      "Control the return to full stretch.",
    ],
    commonMistakes: ["Bending elbows too much (becomes a press)", "Moving too fast", "Short range"],
    alternatives: ["db-press", "chest-fly-machine", "push-up"],
  },
  {
    id: "cable-tricep-pushdown",
    name: "Cable Tricep Pushdown",
    muscleGroup: ["triceps"],
    equipment: ["cable"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "High pulley, rope or bar attachment, elbows tucked.",
      "Push down to full extension, squeeze triceps.",
      "Control return to starting position.",
    ],
    commonMistakes: ["Elbows flaring", "Leaning forward too much", "Partial lockout"],
    alternatives: ["dip", "db-tricep-ext", "skull-crusher"],
  },
  {
    id: "cable-curl",
    name: "Cable Bicep Curl",
    muscleGroup: ["biceps"],
    equipment: ["cable"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Low pulley, underhand grip, elbows at sides.",
      "Curl up fully, squeeze at top.",
      "Lower controlled to full extension.",
    ],
    commonMistakes: ["Swinging", "Elbows moving forward", "Not lowering fully"],
    alternatives: ["db-curl", "pull-up", "bb-curl"],
  },
  {
    id: "face-pull",
    name: "Cable Face Pull",
    muscleGroup: ["rear delts", "rotator cuff", "upper back"],
    equipment: ["cable"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Rope at head height, pull to face with elbows high.",
      "External rotate at end — hands end up behind head.",
      "Return controlled.",
    ],
    commonMistakes: ["Elbows too low", "Too heavy", "No external rotation"],
    alternatives: ["db-lateral-raise", "band-pull-apart", "db-row"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    muscleGroup: ["shoulders", "side delts"],
    equipment: ["cable"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Cable at ankle height on opposite side, single arm.",
      "Raise arm out to side to shoulder height.",
      "Lower controlled, constant tension.",
    ],
    commonMistakes: ["Too heavy", "Swinging", "Going too high"],
    alternatives: ["db-lateral-raise", "machine-lateral-raise", "face-pull"],
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Through",
    muscleGroup: ["glutes", "hamstrings", "lower back"],
    equipment: ["cable"],
    movementPattern: "hinge",
    difficulty: "beginner",
    instructions: [
      "Low pulley, rope between legs, hinge at hips.",
      "Drive hips forward to stand, squeeze glutes at top.",
      "Hinge back slowly for stretch.",
    ],
    commonMistakes: ["Using arms to pull", "Rounding back", "Not reaching full extension"],
    alternatives: ["bb-hip-thrust", "bw-glute-bridge", "db-rdl"],
  },

  // ── MACHINE ──────────────────────────────────────────────────────────────────
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: ["quads", "glutes", "hamstrings"],
    equipment: ["machine"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Feet shoulder-width on platform, back flat.",
      "Lower sled until knees near chest, don't let back peel off.",
      "Press to full extension, don't lock knees.",
    ],
    commonMistakes: ["Knees caving", "Back peeling from pad", "Locking out knees"],
    alternatives: ["bb-squat", "hack-squat", "db-goblet-squat"],
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscleGroup: ["hamstrings"],
    equipment: ["machine"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Lie face down (or seated), pad behind/above ankles.",
      "Curl legs fully toward glutes.",
      "Lower controlled to full extension.",
    ],
    commonMistakes: ["Hips rising", "Partial range", "Using momentum"],
    alternatives: ["db-rdl", "bb-rdl", "good-morning"],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: ["quads"],
    equipment: ["machine"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Seat adjusted so knee joint aligns with machine pivot.",
      "Extend legs fully, squeeze quads at top.",
      "Lower controlled.",
    ],
    commonMistakes: ["Too much weight (knee stress)", "Partial range", "Swinging back"],
    alternatives: ["bb-squat", "leg-press", "bw-squat"],
  },
  {
    id: "chest-fly-machine",
    name: "Chest Fly Machine (Pec Deck)",
    muscleGroup: ["chest", "front delts"],
    equipment: ["machine"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Back flat against pad, forearms on pads.",
      "Bring arms together squeezing chest hard.",
      "Control the return to full stretch.",
    ],
    commonMistakes: ["Going too fast", "Arching back off pad", "Too much weight"],
    alternatives: ["cable-fly", "db-press", "push-up"],
  },
  {
    id: "seated-row-machine",
    name: "Seated Cable Row Machine",
    muscleGroup: ["back", "biceps"],
    equipment: ["machine"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Chest against pad, grip handles.",
      "Pull back squeezing shoulder blades together.",
      "Control return to full arm extension.",
    ],
    commonMistakes: ["Shrugging", "Leaning too far back", "Short range"],
    alternatives: ["cable-row", "db-row", "bb-row"],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    muscleGroup: ["shoulders", "triceps"],
    equipment: ["machine"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Seat adjusted so handles at ear height.",
      "Press straight up to full extension.",
      "Lower controlled to start.",
    ],
    commonMistakes: ["Too wide grip", "Not going full range", "Arching back"],
    alternatives: ["db-shoulder-press", "bb-ohp", "pike-push-up"],
  },
  {
    id: "hack-squat",
    name: "Hack Squat Machine",
    muscleGroup: ["quads", "glutes"],
    equipment: ["machine"],
    movementPattern: "squat",
    difficulty: "intermediate",
    instructions: [
      "Back against pad, feet shoulder-width on platform.",
      "Lower to 90° or deeper, knees track over toes.",
      "Drive up to just before lockout.",
    ],
    commonMistakes: ["Feet too low (knee stress)", "Partial range", "Knees caving"],
    alternatives: ["leg-press", "bb-squat", "bb-front-squat"],
  },
  {
    id: "smith-machine-bench",
    name: "Smith Machine Bench Press",
    muscleGroup: ["chest", "triceps", "shoulders"],
    equipment: ["machine"],
    movementPattern: "push",
    difficulty: "beginner",
    instructions: [
      "Lie on bench under smith bar, unrack.",
      "Lower to lower chest, elbows at 75°.",
      "Press up and rerack.",
    ],
    commonMistakes: ["Flaring elbows", "Bar path restricted unnaturally", "Not engaging stabilizers"],
    alternatives: ["bb-bench", "db-press", "push-up"],
  },

  // ── KETTLEBELL ───────────────────────────────────────────────────────────────
  {
    id: "kb-swing",
    name: "Kettlebell Swing",
    muscleGroup: ["glutes", "hamstrings", "back", "core"],
    equipment: ["kettlebell"],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Hike bell between legs, hinge at hips not squat.",
      "Drive hips forward explosively to swing bell to shoulder height.",
      "Let bell fall back, hinge again — continuous rhythm.",
    ],
    commonMistakes: ["Squatting instead of hinging", "Arms pulling the bell", "Not snapping hips"],
    alternatives: ["bb-hip-thrust", "cable-pull-through", "db-rdl"],
  },
  {
    id: "kb-goblet-squat",
    name: "Kettlebell Goblet Squat",
    muscleGroup: ["quads", "glutes", "core"],
    equipment: ["kettlebell"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Hold bell by horns at chest, squat deep.",
      "Elbows inside knees, chest tall.",
      "Drive through heels to stand.",
    ],
    commonMistakes: ["Heels rising", "Elbows flaring", "Rounding back"],
    alternatives: ["db-goblet-squat", "bw-squat", "bb-squat"],
  },
  {
    id: "kb-press",
    name: "Kettlebell Press",
    muscleGroup: ["shoulders", "triceps", "core"],
    equipment: ["kettlebell"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Bell in rack position (bell resting on forearm), stand tall.",
      "Press overhead to full lockout.",
      "Lower back to rack.",
    ],
    commonMistakes: ["Wrist bending back", "Losing rack position", "Leaning away"],
    alternatives: ["db-shoulder-press", "bb-ohp", "machine-shoulder-press"],
  },
  {
    id: "kb-row",
    name: "Kettlebell Row",
    muscleGroup: ["back", "biceps"],
    equipment: ["kettlebell"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Staggered stance, hinge forward, row bell to hip.",
      "Keep elbow close, squeeze lat at top.",
      "Lower fully, repeat.",
    ],
    commonMistakes: ["Rotating torso", "Short range", "Swinging"],
    alternatives: ["db-row", "cable-row", "bb-row"],
  },
  {
    id: "kb-deadlift",
    name: "Kettlebell Deadlift",
    muscleGroup: ["hamstrings", "glutes", "back"],
    equipment: ["kettlebell"],
    movementPattern: "hinge",
    difficulty: "beginner",
    instructions: [
      "Bell between feet, hip-width stance.",
      "Hinge at hips, grab handle, flat back.",
      "Drive hips to stand tall.",
    ],
    commonMistakes: ["Rounding back", "Squatting the movement", "Bar far from body"],
    alternatives: ["bb-deadlift", "db-rdl", "bw-glute-bridge"],
  },

  // ── BAND / BODYWEIGHT ACCESSORY ───────────────────────────────────────────────
  {
    id: "band-pull-apart",
    name: "Band Pull-Apart",
    muscleGroup: ["rear delts", "upper back", "rotator cuff"],
    equipment: ["bands"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Hold band shoulder-width in front, arms straight.",
      "Pull band apart by spreading arms to sides.",
      "Squeeze shoulder blades at end, return controlled.",
    ],
    commonMistakes: ["Elbows bending", "Too easy a band", "Short range"],
    alternatives: ["face-pull", "db-lateral-raise", "cable-row"],
  },
  {
    id: "band-squat",
    name: "Banded Squat",
    muscleGroup: ["quads", "glutes", "abductors"],
    equipment: ["bands"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Band above knees, feet shoulder-width.",
      "Push knees out against band throughout the squat.",
      "Full depth, drive up.",
    ],
    commonMistakes: ["Letting band collapse knees", "Short depth", "Heels rising"],
    alternatives: ["bw-squat", "db-goblet-squat", "bb-squat"],
  },
  {
    id: "resistance-band-row",
    name: "Resistance Band Row",
    muscleGroup: ["back", "biceps"],
    equipment: ["bands"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Anchor band at chest height, hold ends, step back.",
      "Pull toward chest keeping elbows close.",
      "Squeeze shoulder blades, return slow.",
    ],
    commonMistakes: ["Shrugging", "Too much trunk movement", "Partial range"],
    alternatives: ["cable-row", "db-row", "pull-up"],
  },

  // ── ADDITIONAL MOVEMENTS ─────────────────────────────────────────────────────
  {
    id: "step-up",
    name: "Dumbbell Step-Up",
    muscleGroup: ["quads", "glutes"],
    equipment: ["dumbbell", "box"],
    movementPattern: "squat",
    difficulty: "beginner",
    instructions: [
      "Hold dumbbells, place one foot on box.",
      "Drive through front heel to stand on box.",
      "Step down controlled.",
    ],
    commonMistakes: ["Pushing off back foot", "Leaning forward", "Box too high"],
    alternatives: ["bw-lunge", "db-lunge", "split-squat"],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    muscleGroup: ["core", "lats"],
    equipment: ["bodyweight"],
    movementPattern: "carry",
    difficulty: "advanced",
    instructions: [
      "Kneel behind wheel, arms straight.",
      "Roll out slowly, hips near floor at extension.",
      "Pull back using core and lats.",
    ],
    commonMistakes: ["Sagging hips", "Too far out too soon", "Using hip flexors only"],
    alternatives: ["plank", "hollow-body-hold", "dead-bug"],
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    muscleGroup: ["core", "hip flexors"],
    equipment: ["bodyweight"],
    movementPattern: "carry",
    difficulty: "intermediate",
    instructions: [
      "Lie on back, arms overhead, legs together.",
      "Lift shoulders and legs, lower back pressed to floor.",
      "Hold position breathing steadily.",
    ],
    commonMistakes: ["Lower back arching", "Bending knees to make it easier", "Holding breath"],
    alternatives: ["plank", "ab-wheel-rollout", "dead-bug"],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscleGroup: ["core", "hip flexors"],
    equipment: ["bodyweight"],
    movementPattern: "carry",
    difficulty: "beginner",
    instructions: [
      "Lie on back, arms up, knees at 90°.",
      "Lower opposite arm and leg to floor slowly.",
      "Return and alternate sides, lower back stays flat.",
    ],
    commonMistakes: ["Lower back arching off floor", "Moving too fast", "Holding breath"],
    alternatives: ["plank", "hollow-body-hold", "mountain-climber"],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    muscleGroup: ["hamstrings", "glutes", "lower back"],
    equipment: ["barbell"],
    movementPattern: "hinge",
    difficulty: "intermediate",
    instructions: [
      "Bar on upper back, slight knee bend.",
      "Hinge at hips, push them back, torso parallel to floor.",
      "Drive hips forward to stand, squeeze glutes.",
    ],
    commonMistakes: ["Rounding back", "Bending knees too much", "Too heavy"],
    alternatives: ["bb-rdl", "db-rdl", "cable-pull-through"],
  },
  {
    id: "pike-push-up",
    name: "Pike Push-Up",
    muscleGroup: ["shoulders", "triceps"],
    equipment: ["bodyweight"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Hips high in inverted V position.",
      "Lower head toward floor bending elbows.",
      "Push back up to start.",
    ],
    commonMistakes: ["Hips dropping", "Short range", "Elbows flaring"],
    alternatives: ["db-shoulder-press", "push-up", "machine-shoulder-press"],
  },
  {
    id: "skull-crusher",
    name: "EZ Bar Skull Crusher",
    muscleGroup: ["triceps"],
    equipment: ["barbell", "bench"],
    movementPattern: "push",
    difficulty: "intermediate",
    instructions: [
      "Lie flat, bar overhead with elbows vertical.",
      "Lower bar to forehead by bending elbows only.",
      "Extend back to lockout.",
    ],
    commonMistakes: ["Elbows flaring", "Moving upper arms", "Too heavy"],
    alternatives: ["cable-tricep-pushdown", "dip", "db-tricep-ext"],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: ["biceps", "brachialis", "forearms"],
    equipment: ["dumbbell"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Neutral grip (palms facing in), curl up.",
      "Elbows fixed at sides.",
      "Lower fully.",
    ],
    commonMistakes: ["Swinging body", "Elbows forward", "Too fast"],
    alternatives: ["db-curl", "cable-curl", "pull-up"],
  },
  {
    id: "bb-curl",
    name: "Barbell Bicep Curl",
    muscleGroup: ["biceps", "forearms"],
    equipment: ["barbell"],
    movementPattern: "pull",
    difficulty: "beginner",
    instructions: [
      "Underhand grip, elbows at sides.",
      "Curl fully, squeeze at top.",
      "Lower controlled to full extension.",
    ],
    commonMistakes: ["Swinging", "Short range", "Elbows drifting forward"],
    alternatives: ["db-curl", "cable-curl", "pull-up"],
  },
];

export function getExerciseById(id: string): ExerciseEntry | undefined {
  return EXERCISE_DATABASE.find((e) => e.id === id);
}

export function getAlternatives(id: string): ExerciseEntry[] {
  const ex = getExerciseById(id);
  if (!ex) return [];
  return ex.alternatives
    .map((altId) => getExerciseById(altId))
    .filter((e): e is ExerciseEntry => !!e);
}

export function getByMuscleGroup(muscleGroup: string): ExerciseEntry[] {
  return EXERCISE_DATABASE.filter((e) =>
    e.muscleGroup.some((m) => m.toLowerCase().includes(muscleGroup.toLowerCase()))
  );
}

export function getByEquipment(equipment: string[]): ExerciseEntry[] {
  if (equipment.includes("full_gym")) return EXERCISE_DATABASE;
  return EXERCISE_DATABASE.filter((e) =>
    e.equipment.some((eq) => equipment.includes(eq) || eq === "bodyweight")
  );
}
