const fs=require("fs");const BT="\x60";
const q="\x22";
const OUT='C:/Users/Geric/Desktop/forc3/src/app/coach/history/page.tsx';
const L=[];
L.push(BT+"use client"+BT+";");
L.push("");
L.push("import { useEffect, useState, useMemo } from "+q+"react"+q+";");
L.push("import { useRouter } from "+q+"next/navigation"+q+";");
L.push("import BottomNav from "+q+"@/components/shared/BottomNav"+q+";");
L.push("");
L.push("// ---------------------------------------------------------------------------");
L.push("// Types");
L.push("// ---------------------------------------------------------------------------");
L.push("");
L.push("interface CoachMessage {");
L.push("  id: string;");
L.push("  role: "+q+"user"+q+" | "+q+"coach"+q+";");
L.push("  content: string;");
L.push("  createdAt: string;");
L.push("}");
L.push("");
L.push("interface GroupedMessages {");
L.push("  label: string;");
L.push("  messages: CoachMessage[];");
L.push("}");
