// FORC3 Exercise Database Seed — 150+ exercises covering ALL muscle groups
// Run: npx tsx prisma/seed-exercises.ts

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function slug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function j(arr: string[]) {
  return JSON.stringify(arr);
}

interface ExerciseDef {
  name: string;
  category: string;
  movementPattern: string;
  skillLevel: string;
  muscleGroups: string[];
  secondaryMuscles: string[];
  equipment: string[];
  avoidIfInjury: string[];
  formTips: string[];
  commonMistakes: string[];
  coachingCues: string[];
  alternatives: string[];
}

const EXERCISES: ExerciseDef[] = [
  // ─── CHEST ──────────────────────────────────────────────────────────────────
  {
    name: "Barbell Bench Press",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell", "bench"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Lie flat, feet on floor, arch natural", "Grip just outside shoulder width", "Lower bar to mid-chest with control", "Press up and slightly back toward rack", "Keep shoulder blades retracted throughout"],
    commonMistakes: ["Bouncing bar off chest", "Flaring elbows 90°", "Lifting hips off bench"],
    coachingCues: ["Drive your feet into the floor", "Squeeze the bar like you're bending it", "Touch chest, don't bounce"],
    alternatives: ["Dumbbell Bench Press", "Push Up", "Machine Chest Press"],
  },
  {
    name: "Incline Barbell Bench Press",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["upper chest"], secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell", "bench"], avoidIfInjury: ["shoulder"],
    formTips: ["Set bench to 30-45°", "Grip slightly narrower than flat bench", "Lower to upper chest/clavicle area", "Press up and slightly back", "Keep core braced"],
    commonMistakes: ["Bench angle too steep (shoulder dominant)", "Bar drifting toward neck", "Losing upper back tightness"],
    coachingCues: ["Think upper chest, not shoulders", "Pull the bar apart as you press", "Keep chest up throughout"],
    alternatives: ["Incline Dumbbell Press", "Cable Upper Chest Fly", "Barbell Bench Press"],
  },
  {
    name: "Dumbbell Bench Press",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbells", "bench"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Hold dumbbells at chest level", "Press up and slightly in at top", "Lower with control — elbows 45°", "Full range of motion", "Neutral or pronated grip"],
    commonMistakes: ["Dumbbells too wide at bottom", "Rushing the eccentric", "Inconsistent path"],
    coachingCues: ["Squeeze at the top", "Control the negative — 2-3 seconds down", "Imagine pushing the floor away while lying down"],
    alternatives: ["Barbell Bench Press", "Push Up", "Cable Chest Press"],
  },
  {
    name: "Incline Dumbbell Press",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["upper chest"], secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["dumbbells", "bench"], avoidIfInjury: ["shoulder"],
    formTips: ["30-45° incline", "Start with dumbbells at shoulder level", "Press up and in toward each other", "Lower with control", "Keep lower back on pad"],
    commonMistakes: ["Angle too steep", "Not achieving full stretch at bottom", "Uneven pressing path"],
    coachingCues: ["Push the ceiling away from your upper chest", "Arc the dumbbells together at top", "Control the descent"],
    alternatives: ["Incline Barbell Bench Press", "Cable Upper Fly", "Push Up (incline)"],
  },
  {
    name: "Dumbbell Flyes",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders"],
    equipment: ["dumbbells", "bench"], avoidIfInjury: ["shoulder"],
    formTips: ["Slight bend in elbows throughout", "Lower arms wide until chest fully stretched", "Bring arms back up in arc motion", "Keep chest proud", "Don't lock elbows"],
    commonMistakes: ["Turning it into a press", "Going too heavy", "Losing elbow angle"],
    coachingCues: ["Hug a big tree", "Feel the chest stretch at the bottom", "Squeeze hard at the top"],
    alternatives: ["Cable Crossover", "Pec Deck", "Incline Dumbbell Flyes"],
  },
  {
    name: "Cable Crossover",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders"],
    equipment: ["cable"], avoidIfInjury: ["shoulder"],
    formTips: ["Set cables high for lower chest, low for upper", "Step forward, slight lean", "Bring hands together in front of chest", "Hold squeeze 1 second", "Return with control"],
    commonMistakes: ["Using too much weight and swinging", "Not getting full stretch", "Rounded back"],
    coachingCues: ["Constant tension throughout — don't let cables go slack", "Think hugging motion, not pressing", "Slow the eccentric"],
    alternatives: ["Dumbbell Flyes", "Pec Deck", "Dumbbell Bench Press"],
  },
  {
    name: "Push Up",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders", "triceps", "core"],
    equipment: ["bodyweight"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Hands slightly wider than shoulders", "Body in straight line head to heel", "Lower chest to ground", "Press back up to full extension", "Core braced throughout"],
    commonMistakes: ["Hips sagging", "Partial range of motion", "Head drooping"],
    coachingCues: ["Rigid plank from head to toe", "Chest to the floor", "Drive the floor away"],
    alternatives: ["Dumbbell Bench Press", "Machine Chest Press", "Chest Dip"],
  },
  {
    name: "Chest Dip",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["chest"], secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["bodyweight", "dip bars"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Lean forward to shift emphasis to chest", "Lower until shoulders below elbows", "Press back up to full extension", "Keep elbows slightly flared", "Control the descent"],
    commonMistakes: ["Too upright (becomes tricep-dominant)", "Not going deep enough", "Kipping"],
    coachingCues: ["Lean forward — chest not triceps", "Feel the stretch in chest at bottom", "Full extension but don't lock out hard"],
    alternatives: ["Barbell Bench Press", "Push Up", "Machine Chest Press"],
  },
  {
    name: "Machine Chest Press",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["machine"], avoidIfInjury: [],
    formTips: ["Adjust seat so handles are at chest height", "Keep back flat on pad", "Press out to full extension", "Return with control", "Don't let weight stack touch between reps"],
    commonMistakes: ["Seat too high (shoulder dominant)", "Bouncing weight stack", "Arching excessively"],
    coachingCues: ["Control every rep — no momentum", "Squeeze chest at full extension", "Stay tight on the pad"],
    alternatives: ["Barbell Bench Press", "Dumbbell Bench Press", "Push Up"],
  },
  {
    name: "Pec Deck",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["chest"], secondaryMuscles: ["shoulders"],
    equipment: ["machine"], avoidIfInjury: ["shoulder"],
    formTips: ["Elbows at 90° on pads", "Bring pads together in front of chest", "Hold squeeze 1 second", "Return to slight stretch — don't go beyond perpendicular", "Stay upright"],
    commonMistakes: ["Going too wide behind body", "Using momentum", "Losing upright posture"],
    coachingCues: ["Squeeze at the peak like you're cracking a walnut with your chest", "Keep elbows up", "No bouncing at stretch"],
    alternatives: ["Cable Crossover", "Dumbbell Flyes", "Chest Dip"],
  },

  // ─── BACK ───────────────────────────────────────────────────────────────────
  {
    name: "Barbell Row",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["lats", "upper back"], secondaryMuscles: ["biceps", "rear delts"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back", "wrist_elbow"],
    formTips: ["Hip hinge to about 45° forward lean", "Grip just outside legs", "Pull bar to lower chest/upper abdomen", "Squeeze shoulder blades at top", "Lower with control"],
    commonMistakes: ["Too upright — becomes shrug", "Jerking with lower back", "Bar path too high to neck"],
    coachingCues: ["Pull elbows back and down — not just up", "Think about crushing a pen between your shoulder blades", "Keep spine neutral throughout"],
    alternatives: ["Dumbbell Row", "Seated Cable Row", "T-Bar Row"],
  },
  {
    name: "Dumbbell Row",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["lats", "upper back"], secondaryMuscles: ["biceps"],
    equipment: ["dumbbells"], avoidIfInjury: ["lower_back"],
    formTips: ["Support with one hand and knee on bench", "Keep back parallel to floor", "Pull elbow back and up past torso", "Rotate slightly at top for full contraction", "Lower fully with control"],
    commonMistakes: ["Rotating torso too much", "Using momentum/swinging", "Not getting full range"],
    coachingCues: ["Lead with the elbow, not the hand", "Row from your shoulder blade — think retraction first", "Hold 1 second at top"],
    alternatives: ["Barbell Row", "Seated Cable Row", "Lat Pulldown"],
  },
  {
    name: "Pull Up",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["lats"], secondaryMuscles: ["biceps", "rear delts", "core"],
    equipment: ["bodyweight", "pullup_bar"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Overhand grip, hands slightly wider than shoulders", "Hang at full dead hang", "Pull chest to bar — not chin over bar", "Lead with chest, not chin", "Lower with full control"],
    commonMistakes: ["Kipping instead of strict", "Partial range of motion", "Excessive shrugging at top"],
    coachingCues: ["Pull your elbows to your hips", "Chest to the bar — not chin over bar", "Start from a real dead hang"],
    alternatives: ["Lat Pulldown", "Assisted Pull Up", "Band Pull Up"],
  },
  {
    name: "Chin Up",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["lats", "biceps"], secondaryMuscles: ["rear delts", "core"],
    equipment: ["bodyweight", "pullup_bar"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Underhand grip, shoulder width", "Full dead hang to start", "Pull chin over bar", "Curl with biceps — more bicep-friendly than pull up", "Control the negative"],
    commonMistakes: ["Swinging body", "Half reps", "Neck craning upward"],
    coachingCues: ["Elbows in, biceps engaged", "Drive your chest up — not your chin", "3 second descent"],
    alternatives: ["Pull Up", "Lat Pulldown", "Dumbbell Row"],
  },
  {
    name: "Lat Pulldown",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["lats"], secondaryMuscles: ["biceps", "rear delts"],
    equipment: ["cable"], avoidIfInjury: ["shoulder"],
    formTips: ["Grip slightly wider than shoulders", "Lean back slightly, chest up", "Pull bar to upper chest", "Lead elbows down and back", "Slow return to full extension"],
    commonMistakes: ["Pulling behind the head", "Leaning back too far", "Not fully extending at top"],
    coachingCues: ["Pull your elbows into your back pockets", "Bar to your chin — not behind your head", "Stretch at the top before each rep"],
    alternatives: ["Pull Up", "Dumbbell Row", "Straight Arm Pulldown"],
  },
  {
    name: "Seated Cable Row",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["upper back", "lats"], secondaryMuscles: ["biceps", "rear delts"],
    equipment: ["cable"], avoidIfInjury: ["lower_back"],
    formTips: ["Sit tall, slight knee bend", "Start with arms fully extended and slight forward lean", "Pull handle to lower abdomen", "Drive elbows back and squeeze", "Return with control and stretch forward"],
    commonMistakes: ["Rocking torso for momentum", "Not fully stretching at start", "Pulling too high to chest"],
    coachingCues: ["Initiate with the shoulder blades, not the arms", "Sit up tall throughout", "Feel the stretch before each rep"],
    alternatives: ["Barbell Row", "Dumbbell Row", "T-Bar Row"],
  },
  {
    name: "T-Bar Row",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["upper back", "lats"], secondaryMuscles: ["biceps", "rear delts"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back"],
    formTips: ["Straddle bar, hinge forward", "Grip V-handle or bar with both hands", "Pull to chest", "Keep back flat", "Control descent"],
    commonMistakes: ["Rounding lower back", "Too upright", "Shrugging instead of retracting"],
    coachingCues: ["Keep chest proud throughout", "Row with your elbows", "Think 'break the bar in half'"],
    alternatives: ["Barbell Row", "Seated Cable Row", "Dumbbell Row"],
  },
  {
    name: "Face Pull",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["rear delts"], secondaryMuscles: ["upper back", "external rotators"],
    equipment: ["cable"], avoidIfInjury: [],
    formTips: ["Set cable at face height or higher", "Use rope attachment", "Pull to face, hands going to ears", "Elbows high throughout", "External rotate at end position"],
    commonMistakes: ["Pulling to chest (front delts)", "Letting elbows drop", "Too much weight"],
    coachingCues: ["Pull the rope apart as you pull back", "Elbows above hands at all times", "Think 'double bicep pose' at the end"],
    alternatives: ["Rear Delt Fly", "Band Pull Apart", "Reverse Cable Fly"],
  },
  {
    name: "Straight Arm Pulldown",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["lats"], secondaryMuscles: ["triceps", "core"],
    equipment: ["cable"], avoidIfInjury: ["shoulder"],
    formTips: ["Straight bar or rope at top of cable", "Arms almost fully extended throughout", "Hinge at shoulder — pull bar to thighs", "Squeeze lats hard at bottom", "Slowly return"],
    commonMistakes: ["Bending elbows (becomes pulldown)", "Too much forward lean", "Going too heavy"],
    coachingCues: ["Keep arms straight — this is a lat isolation", "Squeeze like you're trying to put your arms through your hips", "Slow and controlled"],
    alternatives: ["Lat Pulldown", "Pull Up", "Dumbbell Pullover"],
  },
  {
    name: "Deadlift",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["hamstrings", "glutes", "lower back"], secondaryMuscles: ["quads", "lats", "traps"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back"],
    formTips: ["Bar over mid-foot, hip-width stance", "Push hips back and hinge, grip bar", "Big breath, brace core, pull slack out", "Drive through floor, push hips forward", "Stand tall at top — don't hyperextend"],
    commonMistakes: ["Rounding lower back", "Bar drifting away from body", "Jerking off floor — no slack pull"],
    coachingCues: ["Push the floor away, don't pull the bar up", "Bar stays in contact with shins", "Squeeze glutes hard at lockout"],
    alternatives: ["Romanian Deadlift", "Trap Bar Deadlift", "Good Morning"],
  },
  {
    name: "Good Morning",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["hamstrings", "lower back"], secondaryMuscles: ["glutes"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back"],
    formTips: ["Bar on traps like squat", "Slight knee bend", "Hinge forward keeping back flat", "Go until hamstrings are tight", "Drive hips forward to stand"],
    commonMistakes: ["Rounding back", "Going too heavy", "Losing knee bend and leg position"],
    coachingCues: ["Push hips back not down", "Keep chest up as long as possible", "Hamstring stretch — feel it"],
    alternatives: ["Romanian Deadlift", "Stiff Leg Deadlift", "Back Extension"],
  },
  {
    name: "Back Extension",
    category: "strength", movementPattern: "hinge", skillLevel: "beginner",
    muscleGroups: ["lower back"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["machine"], avoidIfInjury: [],
    formTips: ["Hips on pad, feet secured", "Cross arms on chest or behind head", "Lower torso toward floor", "Raise back to horizontal or just above", "Control movement both ways"],
    commonMistakes: ["Hyperextending at top", "Jerky movement", "Too much weight too soon"],
    coachingCues: ["Think 'plank at the top'", "Squeeze glutes as you rise", "Slow and controlled"],
    alternatives: ["Good Morning", "Romanian Deadlift", "Bird Dog"],
  },
  {
    name: "Shrugs",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["traps"], secondaryMuscles: [],
    equipment: ["barbell", "dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Hold weight at sides", "Shrug straight up toward ears", "Hold peak for 1-2 seconds", "Lower with control", "Do not roll shoulders"],
    commonMistakes: ["Rolling shoulders (risk of injury)", "Too much weight with no squeeze", "Partial range"],
    coachingCues: ["Straight up — not forward or back", "Squeeze hard at the top", "Slow negative"],
    alternatives: ["Face Pull", "Dumbbell Shrugs", "Cable Shrugs"],
  },

  // ─── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    name: "Barbell Overhead Press",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["shoulders"], secondaryMuscles: ["triceps", "upper chest", "core"],
    equipment: ["barbell"], avoidIfInjury: ["shoulder", "lower_back"],
    formTips: ["Grip just outside shoulders", "Start at clavicle level", "Press straight up — bar passes face", "Lock out overhead", "Lower with control back to start"],
    commonMistakes: ["Pressing forward instead of straight up", "Hyperextending lower back", "Partial lockout"],
    coachingCues: ["Press your head through at the top", "Keep core braced and glutes squeezed", "Think 'bar over heels'"],
    alternatives: ["Dumbbell Shoulder Press", "Arnold Press", "Machine Shoulder Press"],
  },
  {
    name: "Dumbbell Shoulder Press",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["shoulders"], secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Dumbbells at ear level, elbows slightly forward", "Press up and together overhead", "Full extension at top", "Lower with control", "Seated or standing — both valid"],
    commonMistakes: ["Elbows flaring too wide (behind body)", "Incomplete range", "Arching back excessively"],
    coachingCues: ["Elbows slightly in front — not directly to the side", "Press to full lockout every rep", "Keep core engaged"],
    alternatives: ["Barbell Overhead Press", "Arnold Press", "Machine Shoulder Press"],
  },
  {
    name: "Arnold Press",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["shoulders"], secondaryMuscles: ["triceps"],
    equipment: ["dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Start with palms facing you, dumbbells at chin height", "Press and rotate so palms face out at top", "Reverse the rotation on the way down", "Full range of motion", "Smooth rotation throughout"],
    commonMistakes: ["Not rotating fully", "Too heavy to control rotation", "Rushed movement"],
    coachingCues: ["Smooth rotation builds shoulder stability", "Think front to side as you press", "Control both up and down"],
    alternatives: ["Dumbbell Shoulder Press", "Barbell Overhead Press", "Cable Press"],
  },
  {
    name: "Lateral Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["shoulders"], secondaryMuscles: [],
    equipment: ["dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Stand with slight bend at waist", "Raise arms to side to shoulder height", "Lead with elbows, not hands", "Small 'pouring water' tilt at top", "Lower with control — 3 seconds"],
    commonMistakes: ["Swinging to get weight up", "Raising above shoulder height", "Hands higher than elbows"],
    coachingCues: ["Elbows lead the movement, hands follow", "Imagine pouring water from a pitcher at the top", "Go lighter and feel it working"],
    alternatives: ["Cable Lateral Raise", "Machine Lateral Raise", "Upright Row"],
  },
  {
    name: "Cable Lateral Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["shoulders"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: ["shoulder"],
    formTips: ["Cable at low position, grab with opposite hand", "Raise arm across body and up to side", "Constant tension throughout", "Hold at top", "Lower with control"],
    commonMistakes: ["Too much lean for leverage", "Letting cable go slack", "Going too heavy"],
    coachingCues: ["Constant tension beats heavy weight here", "Lead with the elbow", "Think slow and squeeze"],
    alternatives: ["Lateral Raise", "Machine Lateral Raise", "Dumbbell Shoulder Press"],
  },
  {
    name: "Front Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["shoulders"], secondaryMuscles: [],
    equipment: ["dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Hold dumbbells in front of thighs", "Raise both or alternate to shoulder height", "Palms facing down or inward", "Controlled descent", "Don't lean back"],
    commonMistakes: ["Using momentum", "Going above eye level", "Internal rotation at top"],
    coachingCues: ["Slow and controlled", "Shoulder height is enough", "Don't shrug — isolate the front delt"],
    alternatives: ["Dumbbell Shoulder Press", "Barbell Overhead Press", "Cable Front Raise"],
  },
  {
    name: "Rear Delt Fly",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["rear delts"], secondaryMuscles: ["upper back"],
    equipment: ["dumbbells"], avoidIfInjury: [],
    formTips: ["Hinge forward 45°, chest toward thighs", "Arms hanging, elbows slightly bent", "Raise arms out to the side", "Pinch shoulder blades at top", "Lower with control"],
    commonMistakes: ["Not hinging enough forward", "Shrugging during movement", "Arms going too wide behind body"],
    coachingCues: ["Lead with elbows, not hands", "Feel rear delts and upper back squeeze at top", "Slow and feel it"],
    alternatives: ["Face Pull", "Cable Rear Delt Fly", "Reverse Pec Deck"],
  },
  {
    name: "Upright Row",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["shoulders", "traps"], secondaryMuscles: ["biceps"],
    equipment: ["barbell", "dumbbells"], avoidIfInjury: ["shoulder"],
    formTips: ["Overhand grip, narrow (shoulder-width or inside)", "Pull bar straight up to chin level", "Elbows higher than hands at top", "Lower with control", "Keep bar close to body"],
    commonMistakes: ["Grip too wide (impingement risk)", "Elbows below hands", "Excessive forward lean"],
    coachingCues: ["Elbows drive up first", "Imagine zipping up a jacket", "Control the descent"],
    alternatives: ["Lateral Raise", "Dumbbell Shoulder Press", "Face Pull"],
  },
  {
    name: "Band Pull Apart",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["rear delts"], secondaryMuscles: ["upper back", "external rotators"],
    equipment: ["bands"], avoidIfInjury: [],
    formTips: ["Hold band at shoulder height with straight arms", "Pull band apart horizontally", "Arms end at 180°", "Hold 1 second", "Return with control"],
    commonMistakes: ["Elbows bending", "Not getting full stretch", "Band too thick"],
    coachingCues: ["Keep arms straight throughout", "Pull through to full stretch", "Feel rear delts and squeeze"],
    alternatives: ["Face Pull", "Rear Delt Fly", "Cable Rear Fly"],
  },

  // ─── BICEPS ─────────────────────────────────────────────────────────────────
  {
    name: "Barbell Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["biceps"], secondaryMuscles: ["brachialis"],
    equipment: ["barbell"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Shoulder-width underhand grip", "Upper arms stationary at sides", "Curl to full flexion", "Squeeze at top", "Lower with control — 2-3 seconds"],
    commonMistakes: ["Swinging elbows forward", "Incomplete range of motion", "Using body momentum"],
    coachingCues: ["Lock elbows — pin them to your sides", "Squeeze at the top", "Slow it down on the way down"],
    alternatives: ["Dumbbell Curl", "Cable Curl", "Hammer Curl"],
  },
  {
    name: "Dumbbell Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["biceps"], secondaryMuscles: ["brachialis"],
    equipment: ["dumbbells"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Alternate or both simultaneously", "Start with neutral grip, supinate as you curl", "Full range of motion", "Squeeze hard at peak", "Slow negative"],
    commonMistakes: ["Swinging body", "Not supinating at top", "Dropping weight too fast"],
    coachingCues: ["Rotate palm up as you curl", "Kill the momentum — control every inch", "Think: elbows go nowhere"],
    alternatives: ["Barbell Curl", "Hammer Curl", "Cable Curl"],
  },
  {
    name: "Hammer Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["biceps", "brachialis"], secondaryMuscles: ["forearms"],
    equipment: ["dumbbells"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Neutral grip (palms facing each other)", "Curl straight up", "Elbows stationary", "Full extension at bottom", "Controlled descent"],
    commonMistakes: ["Swinging", "Not holding neutral grip", "Shortening range of motion"],
    coachingCues: ["Thumbs up throughout — neutral grip", "Elbows locked to sides", "Excellent for forearms and brachialis thickness"],
    alternatives: ["Barbell Curl", "Concentration Curl", "Cable Curl"],
  },
  {
    name: "Concentration Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["biceps"], secondaryMuscles: [],
    equipment: ["dumbbells"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Seated, elbow braced against inner thigh", "Curl up to shoulder", "Supinate fully at top", "Slow controlled descent", "No swinging — braced position prevents it"],
    commonMistakes: ["Leaning torso to help lift", "Not bracing elbow properly", "Incomplete range"],
    coachingCues: ["This is pure isolation — feel every inch", "Supinate at top for full bicep contraction", "No momentum whatsoever"],
    alternatives: ["Preacher Curl", "Dumbbell Curl", "Cable Curl"],
  },
  {
    name: "Cable Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["biceps"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Low pulley, straight bar or EZ bar", "Elbows stationary", "Curl to chin height", "Squeeze and hold", "Slow return keeping constant tension"],
    commonMistakes: ["Elbows drifting forward", "Releasing tension at bottom", "Going too heavy"],
    coachingCues: ["Constant tension throughout — don't let cable go slack at bottom", "Lock elbows", "Feel the peak contraction"],
    alternatives: ["Barbell Curl", "Dumbbell Curl", "Preacher Curl"],
  },
  {
    name: "Incline Dumbbell Curl",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["biceps"], secondaryMuscles: [],
    equipment: ["dumbbells", "bench"], avoidIfInjury: ["shoulder"],
    formTips: ["Set bench to 45-60°", "Arms hang fully extended behind body", "Curl from full stretch position", "Supinate at top", "Slow controlled descent"],
    commonMistakes: ["Bench angle too upright (becomes regular curl)", "Swinging arms forward", "Incomplete stretch at bottom"],
    coachingCues: ["Full stretch at bottom = max bicep recruitment", "Feel the long head stretch", "Don't swing — strict form"],
    alternatives: ["Dumbbell Curl", "Cable Curl", "Preacher Curl"],
  },

  // ─── TRICEPS ────────────────────────────────────────────────────────────────
  {
    name: "Close Grip Bench Press",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["triceps"], secondaryMuscles: ["chest", "shoulders"],
    equipment: ["barbell", "bench"], avoidIfInjury: ["wrist_elbow", "shoulder"],
    formTips: ["Shoulder-width grip on barbell", "Keep elbows tucked close to body", "Lower to lower chest", "Press to full lockout", "Control descent"],
    commonMistakes: ["Grip too narrow (wrist strain)", "Flaring elbows", "Incomplete lockout"],
    coachingCues: ["Elbows in — they stay close to torso", "Push through the triceps at the top", "Lockout fully every rep"],
    alternatives: ["Skull Crusher", "Tricep Pushdown", "Diamond Push Up"],
  },
  {
    name: "Skull Crusher",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["triceps"], secondaryMuscles: [],
    equipment: ["barbell", "dumbbells", "bench"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Lie on bench, arms extended overhead", "Lower bar to forehead (or just above)", "Extend arms back to start", "Elbows stationary throughout", "Control the eccentric carefully"],
    commonMistakes: ["Flaring elbows", "Going too heavy", "Bar path drifting"],
    coachingCues: ["Elbows point straight up — don't let them drift out", "Controlled negative for elbow health", "Full extension at top"],
    alternatives: ["Tricep Pushdown", "Overhead Tricep Extension", "Close Grip Bench Press"],
  },
  {
    name: "Tricep Pushdown",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["triceps"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["High cable, rope or straight bar", "Elbows tucked at sides throughout", "Push down to full extension", "Hands separate rope at bottom", "Slow return"],
    commonMistakes: ["Elbows drifting out to sides", "Leaning too far forward", "Not fully extending"],
    coachingCues: ["Keep elbows pinned to ribs throughout", "Squeeze hard at lockout", "Slow the return — don't let cable snap back"],
    alternatives: ["Skull Crusher", "Overhead Tricep Extension", "Diamond Push Up"],
  },
  {
    name: "Overhead Tricep Extension",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["triceps"], secondaryMuscles: [],
    equipment: ["dumbbells", "cable"], avoidIfInjury: ["wrist_elbow", "shoulder"],
    formTips: ["Hold one dumbbell with both hands overhead", "Elbows pointed straight up", "Lower behind head until forearms parallel to floor", "Extend back to overhead", "Keep elbows stationary"],
    commonMistakes: ["Elbows flaring wide", "Not getting full range behind head", "Too heavy"],
    coachingCues: ["Long head of tricep is being stretched — max range is key", "Elbows stay narrow — like they're in a vice", "Full extension at top"],
    alternatives: ["Skull Crusher", "Tricep Pushdown", "Close Grip Bench Press"],
  },
  {
    name: "Tricep Dip",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["triceps"], secondaryMuscles: ["chest", "shoulders"],
    equipment: ["bodyweight"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Hands on bench or parallel bars behind you", "Stay upright — torso vertical for tricep focus", "Lower until elbows at 90°", "Press back to full extension", "Keep elbows narrow"],
    commonMistakes: ["Leaning forward (chest dominant)", "Partial range", "Wrist pain from poor setup"],
    coachingCues: ["Stay upright — lean back minimally", "Elbows track straight back, not out", "Lower slow, press fast"],
    alternatives: ["Tricep Pushdown", "Overhead Tricep Extension", "Close Grip Bench Press"],
  },
  {
    name: "Diamond Push Up",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["triceps"], secondaryMuscles: ["chest"],
    equipment: ["bodyweight"], avoidIfInjury: ["wrist_elbow"],
    formTips: ["Hands forming a diamond/triangle under chest", "Body in straight plank", "Lower chest to hands", "Elbows track back", "Press to lockout"],
    commonMistakes: ["Hands too far forward", "Flaring elbows out", "Hips sagging"],
    coachingCues: ["Elbows go back — not out to sides", "Keep diamond under your chest — not in front", "Rock solid plank"],
    alternatives: ["Tricep Pushdown", "Close Grip Bench Press", "Dip"],
  },
  {
    name: "Cable Kickback",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["triceps"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: [],
    formTips: ["Cable at low position, hinge forward", "Upper arm parallel to floor and stationary", "Extend forearm straight back", "Squeeze at full extension", "Lower with control"],
    commonMistakes: ["Moving upper arm", "Swinging the weight back", "Not fully extending"],
    coachingCues: ["Upper arm locked — only forearm moves", "Squeeze hard at lockout", "Keep it light and feel the tricep"],
    alternatives: ["Overhead Tricep Extension", "Tricep Pushdown", "Skull Crusher"],
  },

  // ─── LEGS — QUADS ───────────────────────────────────────────────────────────
  {
    name: "Barbell Back Squat",
    category: "strength", movementPattern: "squat", skillLevel: "intermediate",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings", "core"],
    equipment: ["barbell"], avoidIfInjury: ["knee", "lower_back"],
    formTips: ["Bar on upper traps, feet shoulder-width", "Break at hips and knees simultaneously", "Track knees over toes throughout", "Descend until thighs parallel or below", "Drive through heels to stand"],
    commonMistakes: ["Knees caving inward", "Excessive forward lean", "Heels rising off floor"],
    coachingCues: ["Sit back and down — not just down", "Push knees out over toes", "Chest stays up proud"],
    alternatives: ["Goblet Squat", "Leg Press", "Bulgarian Split Squat"],
  },
  {
    name: "Front Squat",
    category: "strength", movementPattern: "squat", skillLevel: "advanced",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"], avoidIfInjury: ["wrist_elbow", "shoulder"],
    formTips: ["Bar in front rack or crossed arm position", "Elbows high throughout", "Very upright torso", "Deep squat — chest stays forward", "Drive straight up"],
    commonMistakes: ["Elbows dropping (bar falls)", "Forward lean like back squat", "Heel rise"],
    coachingCues: ["Elbows up — that's what keeps the bar in place", "Sit between your feet — not back", "Most upright squat you'll ever do"],
    alternatives: ["Barbell Back Squat", "Goblet Squat", "Hack Squat"],
  },
  {
    name: "Goblet Squat",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbells", "kettlebells"], avoidIfInjury: ["knee"],
    formTips: ["Hold dumbbell/KB at chest with both hands", "Feet shoulder-width, toes slightly out", "Squat deep — elbows track inside knees at bottom", "Stay upright throughout", "Drive through full foot to stand"],
    commonMistakes: ["Knees caving", "Heel rise", "Weight pulling you forward"],
    coachingCues: ["Elbows push knees out at bottom", "Stay tall and upright", "Great mobility builder — go deep"],
    alternatives: ["Barbell Back Squat", "Leg Press", "Bulgarian Split Squat"],
  },
  {
    name: "Hack Squat",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes"],
    equipment: ["machine"], avoidIfInjury: ["knee"],
    formTips: ["Back flat on pad, feet on platform", "Feet low and narrow for more quad", "Unhook safeties and lower under control", "Descend until thighs below parallel", "Drive through heels to extend"],
    commonMistakes: ["Heels rising off platform", "Knees caving", "Knees locked out hard at top"],
    coachingCues: ["Keep weight through whole foot", "Go deep — the pad supports your back", "Don't lock knees at the top"],
    alternatives: ["Barbell Back Squat", "Leg Press", "Sissy Squat"],
  },
  {
    name: "Leg Press",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["machine"], avoidIfInjury: ["knee", "lower_back"],
    formTips: ["Feet shoulder-width on platform", "Lower platform until knees at 90°", "Push through full foot back to start", "Don't lock knees at full extension", "Don't round lower back"],
    commonMistakes: ["Partial range of motion", "Knees caving", "Letting lower back round off seat"],
    coachingCues: ["Full range — ass doesn't leave seat", "Push through your heels and toes equally", "No knee lockout"],
    alternatives: ["Barbell Back Squat", "Hack Squat", "Goblet Squat"],
  },
  {
    name: "Bulgarian Split Squat",
    category: "strength", movementPattern: "squat", skillLevel: "intermediate",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbells", "bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Rear foot elevated on bench", "Front foot far enough forward", "Lower straight down — knee tracks over toes", "Thigh to parallel or below", "Drive through front heel to stand"],
    commonMistakes: ["Front foot too close (knee way over toes)", "Leaning too far forward", "Rear knee slamming floor"],
    coachingCues: ["Think of this as a single leg squat — control is key", "Front knee tracks second toe", "Hips stay square throughout"],
    alternatives: ["Reverse Lunge", "Leg Press", "Barbell Back Squat"],
  },
  {
    name: "Lunge",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["bodyweight", "dumbbells"], avoidIfInjury: ["knee"],
    formTips: ["Step forward, lower back knee toward floor", "Front thigh parallel to ground", "Front knee over ankle — not over toe", "Push off front foot to return", "Torso stays upright"],
    commonMistakes: ["Front knee caving or going way over toes", "Too short a step", "Leaning torso forward"],
    coachingCues: ["Knee tracks over second toe", "90-90 angles at both knees at bottom", "Push off the floor — power through"],
    alternatives: ["Reverse Lunge", "Bulgarian Split Squat", "Step Up"],
  },
  {
    name: "Reverse Lunge",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["bodyweight", "dumbbells"], avoidIfInjury: ["knee"],
    formTips: ["Step back rather than forward", "Lower back knee toward ground", "Front thigh to parallel", "Push off front foot to return", "More glute-friendly than forward lunge"],
    commonMistakes: ["Step too short", "Front knee caving", "Loss of balance stepping back"],
    coachingCues: ["Step back far enough — front shin stays vertical", "Drive through front heel to stand", "More knee-friendly than forward lunge"],
    alternatives: ["Lunge", "Bulgarian Split Squat", "Step Up"],
  },
  {
    name: "Step Up",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes"],
    equipment: ["bodyweight", "dumbbells"], avoidIfInjury: ["knee"],
    formTips: ["Stand in front of box or bench", "Step up with one foot, drive through heel", "Bring other foot up to stand", "Step back down with control", "Keep torso upright"],
    commonMistakes: ["Pushing off back foot too much", "Leaning over working knee", "Too low a step"],
    coachingCues: ["Drive through the heel of the working leg", "Don't let the back foot help — make front leg do the work", "Control the descent"],
    alternatives: ["Lunge", "Bulgarian Split Squat", "Leg Press"],
  },
  {
    name: "Leg Extension",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: [],
    equipment: ["machine"], avoidIfInjury: ["knee"],
    formTips: ["Adjust seat — knee joint at pivot", "Extend legs to full extension", "Hold peak contraction 1-2 seconds", "Lower with 3-4 second eccentric", "Full range — don't short-rep"],
    commonMistakes: ["Going too heavy", "Partial range", "Swinging torso back"],
    coachingCues: ["Squeeze hard at top — make quads pop", "Slow eccentric protects knees", "It's an isolation — you don't need much weight"],
    alternatives: ["Hack Squat", "Wall Sit", "Goblet Squat"],
  },
  {
    name: "Wall Sit",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Back flat against wall", "Thighs parallel to floor", "Knees at 90°", "Hold position for time", "Arms at sides or extended"],
    commonMistakes: ["Thighs above parallel (too easy)", "Knees going past toes", "Leaning away from wall"],
    coachingCues: ["90° at hips and knees", "Drive your back into the wall", "Breathe — don't hold your breath"],
    alternatives: ["Leg Extension", "Goblet Squat", "Barbell Back Squat"],
  },
  {
    name: "Box Squat",
    category: "strength", movementPattern: "squat", skillLevel: "intermediate",
    muscleGroups: ["quads"], secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back"],
    formTips: ["Set box to parallel height", "Wide stance", "Sit back onto box — don't collapse", "Rock slightly then drive up", "Hips go back first"],
    commonMistakes: ["Bouncing off box", "Knees caving in", "Too narrow stance"],
    coachingCues: ["Sit back — more hip hinge than regular squat", "Pause briefly on box — no bouncing", "Drive the knees out hard on the way up"],
    alternatives: ["Barbell Back Squat", "Goblet Squat", "Hack Squat"],
  },

  // ─── LEGS — HAMSTRINGS ──────────────────────────────────────────────────────
  {
    name: "Romanian Deadlift",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["hamstrings"], secondaryMuscles: ["glutes", "lower back"],
    equipment: ["barbell", "dumbbells"], avoidIfInjury: ["lower_back"],
    formTips: ["Start standing, soft knee bend", "Push hips back as you lower bar along thighs", "Go until you feel full hamstring stretch", "Drive hips forward to return", "Bar stays close to body throughout"],
    commonMistakes: ["Bending knees too much (becomes deadlift)", "Rounding lower back", "Losing neutral spine at bottom"],
    coachingCues: ["Push your hips back — not down", "Feel the hamstring stretch — go until it pulls", "Bar drags along legs the whole way"],
    alternatives: ["Good Morning", "Stiff Leg Deadlift", "Leg Curl"],
  },
  {
    name: "Stiff Leg Deadlift",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["hamstrings"], secondaryMuscles: ["glutes", "lower back"],
    equipment: ["barbell"], avoidIfInjury: ["lower_back"],
    formTips: ["Very slight bend in knees — nearly straight", "Hinge forward as far as flexibility allows", "Keep spine neutral", "Return by squeezing hamstrings and glutes", "Not the same as conventional deadlift"],
    commonMistakes: ["Rounding excessively", "Trying to go to floor without flexibility", "Bar drifting away from body"],
    coachingCues: ["Hamstring flexibility dictates your range — respect it", "Keep a long spine throughout", "Feel the stretch, return when you do"],
    alternatives: ["Romanian Deadlift", "Good Morning", "Nordic Curl"],
  },
  {
    name: "Lying Leg Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["hamstrings"], secondaryMuscles: [],
    equipment: ["machine"], avoidIfInjury: ["knee"],
    formTips: ["Lie face down, ankles under pad", "Curl heels toward glutes", "Hold at peak contraction", "Lower with 3-second eccentric", "Hips stay on pad"],
    commonMistakes: ["Hips rising off pad", "Partial range", "Jerking weight up"],
    coachingCues: ["Keep hips down throughout — no cheating", "Squeeze hamstrings hard at top", "Slow negative is key for hamstring growth"],
    alternatives: ["Romanian Deadlift", "Nordic Curl", "Seated Leg Curl"],
  },
  {
    name: "Seated Leg Curl",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["hamstrings"], secondaryMuscles: [],
    equipment: ["machine"], avoidIfInjury: ["knee"],
    formTips: ["Seated with thigh pad over quads", "Curl legs to full flexion under seat", "Hold peak contraction", "Slow controlled return to full extension", "Different angle targets short head more"],
    commonMistakes: ["Partial range", "Too much weight causing poor form", "Lifting off seat"],
    coachingCues: ["Full range — go as far back as the machine allows", "Squeeze hamstrings at bottom of movement", "Slow the return"],
    alternatives: ["Lying Leg Curl", "Romanian Deadlift", "Nordic Curl"],
  },
  {
    name: "Nordic Curl",
    category: "strength", movementPattern: "pull", skillLevel: "advanced",
    muscleGroups: ["hamstrings"], secondaryMuscles: ["glutes", "core"],
    equipment: ["bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Knees on pad, ankles secured", "Lower torso forward with control", "Use hamstrings to resist gravity — go as far as you can", "Catch yourself with hands if needed", "Pull back up with hamstrings"],
    commonMistakes: ["Going too fast and just falling", "Not building up to full reps gradually", "Hips breaking (butt sticking out)"],
    coachingCues: ["Lean forward slowly — this is brutal but builds strong hamstrings", "Catch the fall — don't crash", "Build up: start with just the lowering phase"],
    alternatives: ["Romanian Deadlift", "Lying Leg Curl", "Good Morning"],
  },
  {
    name: "Single Leg RDL",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["hamstrings"], secondaryMuscles: ["glutes", "core"],
    equipment: ["dumbbells", "bodyweight"], avoidIfInjury: ["lower_back"],
    formTips: ["Stand on one leg, slight knee bend", "Hinge forward — free leg goes back as counterbalance", "Lower dumbbell toward ground", "Return by squeezing glute and hamstring of working leg", "Keep spine neutral throughout"],
    commonMistakes: ["Hip rotating open (both hips should stay square)", "Losing balance from moving too fast", "Knee locking straight"],
    coachingCues: ["Think 'airplane' — body and back leg form a T", "Hips stay square to the floor", "Feel it in the working hamstring"],
    alternatives: ["Romanian Deadlift", "Glute Bridge", "Lying Leg Curl"],
  },

  // ─── LEGS — GLUTES ──────────────────────────────────────────────────────────
  {
    name: "Barbell Hip Thrust",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["glutes"], secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench"], avoidIfInjury: [],
    formTips: ["Shoulders on bench edge, bar across hip crease", "Feet flat, hip-width", "Drive hips up to full extension", "Squeeze glutes hard at top — hold 1 second", "Lower with control"],
    commonMistakes: ["Not reaching full hip extension", "Hyperextending lower back at top", "Bar rolling during movement"],
    coachingCues: ["Drive hips to ceiling — squeeze your butt like you mean it", "At the top: body forms a table — hips level with knees and shoulders", "Posterior pelvic tilt at top — no arch"],
    alternatives: ["Glute Bridge", "Single Leg Hip Thrust", "Sumo Deadlift"],
  },
  {
    name: "Glute Bridge",
    category: "strength", movementPattern: "hinge", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Lie on back, knees bent, feet flat", "Drive hips up by squeezing glutes", "Pause at top with full glute squeeze", "Lower with control", "Can add weight across hips to progress"],
    commonMistakes: ["Arching lower back instead of squeezing glutes", "Feet too far away — hamstring dominant", "No pause at top"],
    coachingCues: ["Squeeze your glutes FIRST then push", "Posterior pelvic tilt — abs tight too", "Bodyweight version is still hard if you do it right"],
    alternatives: ["Barbell Hip Thrust", "Single Leg Glute Bridge", "Donkey Kick"],
  },
  {
    name: "Single Leg Glute Bridge",
    category: "strength", movementPattern: "hinge", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Lie on back, one knee bent, one leg extended up", "Drive working hip up to ceiling", "Squeeze glute at top", "Lower with control", "Great for addressing imbalances"],
    commonMistakes: ["Rotating hips — keep them level", "Working leg foot too close or far", "No full squeeze at top"],
    coachingCues: ["Keep both hips level — fight the rotation", "Squeeze only the working glute", "Build each side equally"],
    alternatives: ["Glute Bridge", "Barbell Hip Thrust", "Donkey Kick"],
  },
  {
    name: "Cable Kickback",
    category: "strength", movementPattern: "hinge", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: [],
    formTips: ["Ankle cuff attachment at low cable", "Hinge forward slightly, hold machine", "Kick leg straight back and up", "Squeeze glute at top", "Return with control"],
    commonMistakes: ["Swinging leg with momentum", "Too much rotation at hips", "Going too heavy"],
    coachingCues: ["Squeeze your glute at the top — not your lower back", "Hip extension, not spine hyperextension", "Slow and feel the glute"],
    alternatives: ["Donkey Kick", "Barbell Hip Thrust", "Glute Bridge"],
  },
  {
    name: "Donkey Kick",
    category: "strength", movementPattern: "hinge", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Start on hands and knees", "Keep core stable", "Drive one leg up toward ceiling, knee bent 90°", "Squeeze glute at top", "Return without touching floor and repeat"],
    commonMistakes: ["Rotating hips to get leg higher", "Arching lower back", "Foot flexion instead of driving heel up"],
    coachingCues: ["Drive your heel up toward the ceiling", "Keep hips square to floor", "Squeeze glute — not lower back"],
    alternatives: ["Glute Bridge", "Cable Kickback", "Hip Thrust"],
  },
  {
    name: "Sumo Deadlift",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["glutes"], secondaryMuscles: ["hamstrings", "quads", "lower back"],
    equipment: ["barbell"], avoidIfInjury: ["hip_mobility", "lower_back"],
    formTips: ["Wide stance, toes angled out", "Grip inside legs on bar", "Hips much lower than conventional", "Drive knees out, chest up", "Stand with hips forward at top"],
    commonMistakes: ["Stance too wide (hip impingement)", "Knees caving in", "Bar drifting forward"],
    coachingCues: ["Push the floor apart with your feet", "Drive your knees out over toes", "Your torso is more upright than conventional"],
    alternatives: ["Conventional Deadlift", "Romanian Deadlift", "Barbell Hip Thrust"],
  },
  {
    name: "Clamshell",
    category: "strength", movementPattern: "rotate", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: [],
    equipment: ["bodyweight", "bands"], avoidIfInjury: ["hip_mobility"],
    formTips: ["Lie on side, hips stacked, knees bent 45°", "Keep feet together", "Rotate top knee open toward ceiling", "Hold 2 seconds at peak", "Lower with control"],
    commonMistakes: ["Hips rolling back", "Not getting full range", "Moving too fast"],
    coachingCues: ["Open like a clamshell — don't let hips roll", "Add a band for more resistance", "Feel glute medius working on the outside of your hip"],
    alternatives: ["Fire Hydrant", "Cable Kickback", "Hip Abduction Machine"],
  },
  {
    name: "Fire Hydrant",
    category: "strength", movementPattern: "rotate", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Start on hands and knees", "Keep knee bent 90°", "Lift leg out to side like a dog", "Raise to hip height or above", "Lower with control"],
    commonMistakes: ["Rotating torso", "Not going high enough", "Losing neutral spine"],
    coachingCues: ["Core stays braced — only leg moves", "Get that leg high — fire hydrant to the max", "Great glute activation warm-up"],
    alternatives: ["Clamshell", "Donkey Kick", "Hip Thrust"],
  },

  // ─── CALVES ─────────────────────────────────────────────────────────────────
  {
    name: "Standing Calf Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["calves"], secondaryMuscles: [],
    equipment: ["machine", "bodyweight"], avoidIfInjury: [],
    formTips: ["Balls of feet on edge of platform", "Full stretch at bottom — heels below platform", "Rise to full tiptoe at top", "Hold peak contraction 1-2 seconds", "Slow controlled descent"],
    commonMistakes: ["Partial range — only going halfway", "Bouncing at bottom", "Knees bent"],
    coachingCues: ["Full stretch at bottom is non-negotiable", "Rise all the way to tiptoe", "3-second negative — calves are stubborn and need slow reps"],
    alternatives: ["Seated Calf Raise", "Single Leg Calf Raise", "Leg Press Calf Raise"],
  },
  {
    name: "Seated Calf Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["calves"], secondaryMuscles: [],
    equipment: ["machine"], avoidIfInjury: [],
    formTips: ["Pad just above knees, balls of feet on platform", "Lower heels for full stretch", "Rise to tippy toes", "Hold at top", "Targets soleus (inner calf) more than standing"],
    commonMistakes: ["No stretch at bottom", "Too light with no resistance", "Bouncing"],
    coachingCues: ["Hit the full range every single rep", "Different from standing version — both needed for full calf development", "Squeeze at top"],
    alternatives: ["Standing Calf Raise", "Single Leg Calf Raise", "Donkey Calf Raise"],
  },
  {
    name: "Leg Press Calf Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["calves"], secondaryMuscles: [],
    equipment: ["machine"], avoidIfInjury: ["knee"],
    formTips: ["Sit in leg press machine with balls of feet at bottom of platform", "Legs nearly straight (slight bend)", "Push platform by pointing toes", "Full range — toes go out fully, heels go in fully", "Control movement"],
    commonMistakes: ["Knees bending during movement", "Partial range", "Moving too fast"],
    coachingCues: ["Balls of feet — not arches", "Full point and full flex", "Control it — don't let weight snap back"],
    alternatives: ["Standing Calf Raise", "Seated Calf Raise", "Single Leg Calf Raise"],
  },
  {
    name: "Single Leg Calf Raise",
    category: "strength", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["calves"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Stand on one foot on step edge", "Hold wall for balance", "Full stretch at bottom", "Rise to full tiptoe", "Slow controlled movement"],
    commonMistakes: ["Rushing through reps", "Not getting full stretch", "Too much hold for balance"],
    coachingCues: ["Best bodyweight calf exercise — go slow", "Full range — go deep on that stretch", "Build each leg equally"],
    alternatives: ["Standing Calf Raise", "Seated Calf Raise", "Leg Press Calf Raise"],
  },

  // ─── CORE ───────────────────────────────────────────────────────────────────
  {
    name: "Plank",
    category: "strength", movementPattern: "isometric", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"], avoidIfInjury: ["wrist_elbow", "shoulder"],
    formTips: ["Forearms on ground, elbows under shoulders", "Body in straight line head to heel", "Squeeze glutes and abs together", "Don't let hips sag or pike up", "Hold steady — breathe"],
    commonMistakes: ["Hips sagging", "Hips too high (pike position)", "Holding breath"],
    coachingCues: ["Squeeze glutes AND abs — both at once", "Think 'rigid board'", "If you can hold perfectly for 1 minute you're good — then add difficulty"],
    alternatives: ["Ab Wheel Rollout", "Dead Bug", "Hollow Body Hold"],
  },
  {
    name: "Side Plank",
    category: "strength", movementPattern: "isometric", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["bodyweight"], avoidIfInjury: ["shoulder"],
    formTips: ["Forearm on ground, elbow under shoulder", "Stack feet or stagger for stability", "Hips lifted — body in diagonal line", "Don't let hips sag", "Hold steady"],
    commonMistakes: ["Hips dropping", "Top hip rotating forward", "Shoulder crunching toward ear"],
    coachingCues: ["Hips stay high throughout", "Great for anti-lateral flexion strength", "Stack feet for more challenge"],
    alternatives: ["Plank", "Pallof Press", "Dead Bug"],
  },
  {
    name: "Ab Wheel Rollout",
    category: "strength", movementPattern: "push", skillLevel: "intermediate",
    muscleGroups: ["core"], secondaryMuscles: ["lats", "shoulders"],
    equipment: ["bodyweight"], avoidIfInjury: ["lower_back", "shoulder"],
    formTips: ["Kneel with wheel in hands", "Roll forward keeping back flat", "Go as far as you can without losing form", "Pull back using abs and lats", "Slow and controlled throughout"],
    commonMistakes: ["Lower back arching (too far without strength)", "Going too far too soon", "Arms only — no core engagement"],
    coachingCues: ["Hollow body position throughout — tuck pelvis", "Abs brace BEFORE you roll forward", "Build up your range — this is brutally hard"],
    alternatives: ["Plank", "Dragon Flag", "Cable Crunch"],
  },
  {
    name: "Hanging Leg Raise",
    category: "strength", movementPattern: "pull", skillLevel: "intermediate",
    muscleGroups: ["core"], secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight", "pullup_bar"], avoidIfInjury: ["shoulder"],
    formTips: ["Hang from bar, arms straight", "Tuck pelvis — don't let lower back arch", "Raise legs to parallel or higher", "Control descent — don't swing", "Exhale as you raise"],
    commonMistakes: ["Swinging momentum", "Using hip flexors only (legs instead of abs)", "Lower back arching"],
    coachingCues: ["Posterior pelvic tilt — tuck your butt as you raise", "Think about raising your hips, not just your feet", "Control the descent completely"],
    alternatives: ["Plank", "Cable Crunch", "Decline Crunch"],
  },
  {
    name: "Cable Crunch",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: [],
    equipment: ["cable"], avoidIfInjury: [],
    formTips: ["Kneel below high cable with rope", "Hold rope at ears or sides of head", "Crunch torso toward thighs", "Hold 2 seconds at bottom", "Return with control — don't lose tension"],
    commonMistakes: ["Pulling with arms instead of abs", "Hips moving (hip flexion instead of spinal flexion)", "Standing up between reps"],
    coachingCues: ["Move only at the spine — your hips don't move", "Exhale hard at the bottom", "This is one of the best weighted ab exercises — learn it properly"],
    alternatives: ["Decline Crunch", "Hanging Leg Raise", "Ab Wheel Rollout"],
  },
  {
    name: "Russian Twist",
    category: "strength", movementPattern: "rotate", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight", "dumbbells"], avoidIfInjury: ["lower_back"],
    formTips: ["Sit with knees bent, feet elevated or on floor", "Lean back slightly — core engaged", "Hold weight at chest and rotate side to side", "Touch ground on each side", "Keep core tight throughout"],
    commonMistakes: ["Moving the weight, not rotating the torso", "Feet flat (too easy)", "Holding breath"],
    coachingCues: ["Rotate from your midsection — think about your belly button moving side to side", "Feet up increases difficulty", "Slow and controlled"],
    alternatives: ["Pallof Press", "Landmine Rotation", "Dead Bug"],
  },
  {
    name: "Dead Bug",
    category: "strength", movementPattern: "isometric", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Lie on back, arms to ceiling, knees at 90°", "Press lower back into floor — keep it there", "Extend opposite arm/leg toward floor", "Return to start without back lifting", "Alternate sides"],
    commonMistakes: ["Lower back arching off floor", "Moving both arms or both legs", "Moving too fast"],
    coachingCues: ["Lower back glued to floor — that's the whole challenge", "Slow and deliberate — this isn't easy done properly", "Breathe out as you extend"],
    alternatives: ["Plank", "Bird Dog", "Hollow Body Hold"],
  },
  {
    name: "Bird Dog",
    category: "strength", movementPattern: "isometric", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["lower back", "glutes"],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Start on hands and knees, neutral spine", "Extend opposite arm and leg simultaneously", "Hold 2-3 seconds at extension", "Return without rotating hips", "Keep core braced throughout"],
    commonMistakes: ["Rotating hips when extending", "Losing neutral spine", "Moving too fast"],
    coachingCues: ["Long spine from fingertips to toes at extension", "Keep hips level — both hip bones face down", "Core braced before each extension"],
    alternatives: ["Dead Bug", "Plank", "Back Extension"],
  },
  {
    name: "Pallof Press",
    category: "strength", movementPattern: "isometric", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["shoulders"],
    equipment: ["cable", "bands"], avoidIfInjury: [],
    formTips: ["Cable at chest height, stand perpendicular to machine", "Hold handle at chest", "Press out to full arm extension", "Hold 2 seconds", "Return to chest — don't rotate"],
    commonMistakes: ["Rotating toward or away from cable", "Not engaging core to resist", "Standing too far from cable"],
    coachingCues: ["Anti-rotation — the goal is NOT to rotate", "Core braces against the pull", "The further from cable, the harder"],
    alternatives: ["Plank", "Side Plank", "Russian Twist"],
  },
  {
    name: "Hollow Body Hold",
    category: "strength", movementPattern: "isometric", skillLevel: "intermediate",
    muscleGroups: ["core"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Lie on back, arms overhead", "Press lower back to floor", "Raise arms, shoulders, legs off floor slightly", "Body forms a slight dish shape", "Hold — breathe shallow"],
    commonMistakes: ["Lower back not pressed to floor", "Holding breath", "Legs too low (increases difficulty — not always wrong)"],
    coachingCues: ["Lower back to floor — that's the foundation of this movement", "Scale by bending knees", "Foundation of gymnastics — build it strong"],
    alternatives: ["Plank", "Dead Bug", "Ab Wheel Rollout"],
  },
  {
    name: "Dragon Flag",
    category: "strength", movementPattern: "isometric", skillLevel: "advanced",
    muscleGroups: ["core"], secondaryMuscles: ["lats", "lower back"],
    equipment: ["bodyweight"], avoidIfInjury: ["lower_back", "shoulder"],
    formTips: ["Grip bench behind head", "Raise body to vertical with just shoulders on bench", "Lower straight as a board toward parallel", "Fight to hold position", "Return straight up"],
    commonMistakes: ["Hips pike (not flat enough)", "Going too fast", "Attempting before having hollow body strength"],
    coachingCues: ["Body must stay perfectly rigid like a plank", "Only shoulders stay on bench", "Hardest ab exercise that exists — build up to it"],
    alternatives: ["Hanging Leg Raise", "Hollow Body Hold", "Ab Wheel Rollout"],
  },
  {
    name: "Decline Crunch",
    category: "strength", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: [],
    equipment: ["bodyweight"], avoidIfInjury: [],
    formTips: ["Secure feet on decline bench", "Hands behind head or crossed on chest", "Curl torso up toward knees", "Hold 2 seconds at top", "Lower with control"],
    commonMistakes: ["Pulling neck with hands", "Using momentum to swing up", "Incomplete range"],
    coachingCues: ["Exhale and crunch — pull ribs to hips", "Don't pull your neck", "Full range — get your shoulder blades off the bench"],
    alternatives: ["Cable Crunch", "Hanging Leg Raise", "Ab Wheel Rollout"],
  },
  {
    name: "Farmers Carry",
    category: "strength", movementPattern: "carry", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["traps", "forearms", "glutes"],
    equipment: ["dumbbells", "kettlebells"], avoidIfInjury: [],
    formTips: ["Pick up heavy weights — one in each hand", "Stand tall — don't lean", "Walk with purpose — short controlled steps", "Core braced throughout", "Put down safely at end"],
    commonMistakes: ["Leaning to one side", "Hunching shoulders", "Weights too light to be challenging"],
    coachingCues: ["Walk tall like you own the place", "Brace your core like a punch is coming", "Go heavy — this builds everything"],
    alternatives: ["Suitcase Carry", "Plank", "Dead Bug"],
  },

  // ─── FULL BODY / COMPOUND ────────────────────────────────────────────────────
  {
    name: "Power Clean",
    category: "olympic", movementPattern: "pull", skillLevel: "advanced",
    muscleGroups: ["quads", "hamstrings", "glutes"], secondaryMuscles: ["shoulders", "traps", "core"],
    equipment: ["barbell"], avoidIfInjury: ["shoulder", "wrist_elbow", "lower_back"],
    formTips: ["Start position like deadlift", "First pull: bar to knees keeping back angle", "Second pull: explosively extend hips — triple extension", "Receive bar in front rack at shoulder height", "Catch in quarter squat then stand"],
    commonMistakes: ["Early arm pull (using arms to lift instead of hips)", "Bar drifting forward off body", "Soft catch position"],
    coachingCues: ["Jump and shrug — then receive", "Hips extend first, then shrug, then pull under", "Explosive hips are everything"],
    alternatives: ["Hang Clean", "Barbell Row", "Deadlift"],
  },
  {
    name: "Hang Clean",
    category: "olympic", movementPattern: "pull", skillLevel: "advanced",
    muscleGroups: ["quads", "glutes", "hamstrings"], secondaryMuscles: ["traps", "shoulders"],
    equipment: ["barbell"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Start with bar hanging at hip crease", "Slightly push hips back then explosively drive forward", "Shrug and pull under to catch in rack", "Receive in quarter squat", "Stand tall"],
    commonMistakes: ["Bar swinging away from body", "Early arm pull", "No hip drive"],
    coachingCues: ["Hip pop is everything — massive extension", "Think 'jump into the rack position'", "Faster under the bar"],
    alternatives: ["Power Clean", "Kettlebell Swing", "Barbell Row"],
  },
  {
    name: "Thruster",
    category: "olympic", movementPattern: "push", skillLevel: "advanced",
    muscleGroups: ["quads", "glutes"], secondaryMuscles: ["shoulders", "triceps", "core"],
    equipment: ["barbell", "dumbbells"], avoidIfInjury: ["shoulder", "lower_back"],
    formTips: ["Front rack position", "Squat all the way down", "As you rise, use hip drive to propel bar overhead", "Lock out completely overhead", "Fluid transition squat to press"],
    commonMistakes: ["Pausing at the top of squat before pressing", "Not using leg drive for the press", "Poor front rack position"],
    coachingCues: ["One fluid movement — squat into press", "Hip drive sends the bar up", "Lock out at the top — arms overhead"],
    alternatives: ["Front Squat", "Barbell Overhead Press", "Goblet Squat"],
  },
  {
    name: "Burpee",
    category: "cardio", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["quads", "chest"], secondaryMuscles: ["shoulders", "core", "glutes"],
    equipment: ["bodyweight"], avoidIfInjury: ["wrist_elbow", "shoulder", "knee"],
    formTips: ["Stand → hands to floor → jump feet back to plank", "Do push up (optional)", "Jump feet forward → jump up with arms overhead", "Land softly", "Move through all positions smoothly"],
    commonMistakes: ["Rushing with poor form", "No full hip extension at top", "Slamming into plank position"],
    coachingCues: ["Smooth transitions beat fast sloppy ones", "Full extension at top — jump for real", "Scale by stepping out instead of jumping"],
    alternatives: ["Mountain Climber", "Jump Squat", "Box Jump"],
  },
  {
    name: "Turkish Get Up",
    category: "strength", movementPattern: "carry", skillLevel: "advanced",
    muscleGroups: ["core"], secondaryMuscles: ["shoulders", "glutes", "quads"],
    equipment: ["kettlebells", "dumbbells"], avoidIfInjury: ["shoulder", "wrist_elbow"],
    formTips: ["Start on back, weight pressed overhead in right hand", "Roll to elbow, then hand", "Bring right leg through to kneeling", "Stand up — weight stays overhead throughout", "Reverse the movement to lie down"],
    commonMistakes: ["Eye not tracking the weight (critical safety)", "Rushing through positions", "Elbow locking out"],
    coachingCues: ["Eyes on the weight at all times", "Each position should be stable before moving", "Master this bodyweight before adding weight"],
    alternatives: ["Plank", "Farmers Carry", "Overhead Press"],
  },
  {
    name: "Kettlebell Swing",
    category: "strength", movementPattern: "hinge", skillLevel: "intermediate",
    muscleGroups: ["glutes", "hamstrings"], secondaryMuscles: ["core", "shoulders"],
    equipment: ["kettlebells"], avoidIfInjury: ["lower_back"],
    formTips: ["Hip hinge start — not a squat", "Drive hips forward explosively", "Let KB swing to chest height naturally", "On way back: hike KB back between legs", "Power from hips — not arms"],
    commonMistakes: ["Squatting the swing (hips too low)", "Pulling KB up with arms", "Rounding lower back"],
    coachingCues: ["Hinge, not squat — think deadlift mechanics", "Hips do the work, arms just hold on", "Snap your hips forward like closing a car door"],
    alternatives: ["Barbell Hip Thrust", "Deadlift", "Good Morning"],
  },
  {
    name: "Box Jump",
    category: "cardio", movementPattern: "squat", skillLevel: "intermediate",
    muscleGroups: ["quads", "glutes"], secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Stand in front of box", "Dip into quarter squat", "Swing arms and jump onto box", "Land softly with bent knees", "Step down — don't jump down"],
    commonMistakes: ["Landing stiff-legged", "Box too high — ego vs smart training", "Jumping down (Achilles risk)"],
    coachingCues: ["Jump and land softly — quiet feet", "Step down every time", "Pull toes up in flight — land on full foot"],
    alternatives: ["Jump Squat", "Step Up", "Squat"],
  },
  {
    name: "Jump Squat",
    category: "cardio", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads", "glutes"], secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Stand shoulder-width", "Squat down", "Explode up from bottom of squat", "Get full extension", "Land softly with bent knees"],
    commonMistakes: ["Not squatting deep enough before jumping", "Hard landing", "No arm drive"],
    coachingCues: ["Down THEN up — not a simultaneous motion", "Land soft — absorb with your legs", "Arms help — swing them up as you jump"],
    alternatives: ["Box Jump", "Barbell Back Squat", "Leg Press"],
  },
  {
    name: "Rowing Machine",
    category: "cardio", movementPattern: "pull", skillLevel: "beginner",
    muscleGroups: ["lats", "hamstrings"], secondaryMuscles: ["quads", "core", "biceps"],
    equipment: ["cardio_machines"], avoidIfInjury: ["lower_back"],
    formTips: ["Drive with legs first — big push", "Lean back slightly as legs extend", "Then pull handle to lower chest", "Return: arms first, then forward lean, then knees bend", "Sequence: legs, back, arms / arms, back, legs"],
    commonMistakes: ["Pulling with arms first", "Not using legs enough", "Hunching back"],
    coachingCues: ["Power comes from your legs — think 80% legs, 20% arms", "Legs, body, arms on drive — reverse on recovery", "Long smooth strokes beat fast choppy ones"],
    alternatives: ["Barbell Row", "Seated Cable Row", "Deadlift"],
  },
  {
    name: "Battle Ropes",
    category: "cardio", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["shoulders"], secondaryMuscles: ["core", "biceps"],
    equipment: ["cardio_machines"], avoidIfInjury: ["shoulder"],
    formTips: ["Stand athletic with slight squat", "Alternate waves or slam together", "Keep core braced", "Full arm range of motion", "Keep moving for set duration"],
    commonMistakes: ["Standing upright (less power)", "Small range of motion", "Stopping and starting"],
    coachingCues: ["Athletic stance unlocks power", "Big waves — go full range", "Keep the intensity consistent throughout the interval"],
    alternatives: ["Jump Rope", "Burpee", "Assault Bike Sprint"],
  },
  {
    name: "Jump Rope",
    category: "cardio", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["calves"], secondaryMuscles: ["core", "shoulders"],
    equipment: ["bodyweight"], avoidIfInjury: ["knee"],
    formTips: ["Elbows at sides, wrists do the work", "Slight jump — just enough to clear rope", "Land on balls of feet", "Keep rhythm consistent", "Look forward"],
    commonMistakes: ["Jumping too high", "Using arms too much", "Landing hard on heels"],
    coachingCues: ["Small controlled jumps — efficiency over spectacle", "Wrists rotate the rope, not whole arms", "Consistent rhythm is everything"],
    alternatives: ["Battle Ropes", "Burpee", "Running"],
  },
  {
    name: "Mountain Climber",
    category: "cardio", movementPattern: "push", skillLevel: "beginner",
    muscleGroups: ["core"], secondaryMuscles: ["shoulders", "hip flexors"],
    equipment: ["bodyweight"], avoidIfInjury: ["wrist_elbow", "shoulder"],
    formTips: ["Start in push up position", "Drive one knee toward chest", "Quickly switch legs", "Keep hips level — don't pike", "Move at your target pace"],
    commonMistakes: ["Hips rising too high", "Losing plank position", "Feet not going far enough forward"],
    coachingCues: ["Hips stay level — fight the pike", "Drive knee to chest — not just halfway", "Control the pace — speed is relative"],
    alternatives: ["Plank", "Burpee", "High Knees"],
  },
  {
    name: "Man Maker",
    category: "strength", movementPattern: "push", skillLevel: "advanced",
    muscleGroups: ["quads", "chest"], secondaryMuscles: ["shoulders", "back", "core"],
    equipment: ["dumbbells"], avoidIfInjury: ["lower_back", "shoulder", "wrist_elbow"],
    formTips: ["Hold dumbbells in push up position", "Do push up", "Row each dumbbell (alternating)", "Jump feet forward between dumbbells", "Power clean and press the dumbbells overhead", "That's one rep"],
    commonMistakes: ["Rushing through steps", "Losing plank position", "Poor clean form"],
    coachingCues: ["Each component matters — don't skip steps", "Control the plank portions especially", "Full body conditioning — expect to be gassed"],
    alternatives: ["Burpee", "Thruster", "Dumbbell Complex"],
  },
  {
    name: "Lunge (Walking)",
    category: "strength", movementPattern: "squat", skillLevel: "beginner",
    muscleGroups: ["quads", "glutes"], secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight", "dumbbells"], avoidIfInjury: ["knee"],
    formTips: ["Stand tall with dumbbells at sides", "Step forward with a long stride", "Lower back knee toward floor", "Keep torso upright and front shin near vertical", "Drive through front heel and continue walking"],
    commonMistakes: ["Front knee caving inward", "Steps too short", "Leaning too far forward"],
    coachingCues: ["Long stride, smooth rhythm", "Control the descent every rep", "Stay tall through your trunk"],
    alternatives: ["Bulgarian Split Squat", "Step Up", "Goblet Squat"],
  },
  {
    name: "Glute Ham Raise",
    category: "strength", movementPattern: "hinge", skillLevel: "advanced",
    muscleGroups: ["hamstrings", "glutes"], secondaryMuscles: ["core", "lower back"],
    equipment: ["ghd_machine"], avoidIfInjury: ["knee", "lower_back"],
    formTips: ["Secure ankles and set knees on pad", "Start upright with hips extended", "Lower torso under control while keeping hips extended", "Pull back up with hamstrings and glutes", "Use hands for assistance if needed"],
    commonMistakes: ["Breaking at hips and folding over", "Dropping too fast", "Using momentum to rebound"],
    coachingCues: ["Keep a straight line from knees to shoulders", "Control the eccentric, explode up", "Use assistance only as needed"],
    alternatives: ["Nordic Curl", "Romanian Deadlift", "Lying Leg Curl"],
  },
  {
    name: "Banded Clamshell",
    category: "strength", movementPattern: "rotate", skillLevel: "beginner",
    muscleGroups: ["glutes"], secondaryMuscles: ["core"],
    equipment: ["bands"], avoidIfInjury: ["hip"],
    formTips: ["Lie on your side with hips stacked", "Place mini-band above knees", "Keep feet together and open top knee", "Pause briefly at top", "Lower slowly without rolling hips back"],
    commonMistakes: ["Rolling hips backward", "Band too heavy causing momentum", "Not controlling the lowering phase"],
    coachingCues: ["Move from the hip, not the lower back", "Small range with full control", "Feel side glute burn, not quads"],
    alternatives: ["Cable Kickback", "Hip Abduction Machine", "Single Leg Glute Bridge"],
  },
];

async function main() {
  console.log("🏋️ Seeding exercise database...");

  let created = 0;
  let skipped = 0;

  for (const ex of EXERCISES) {
    const exerciseSlug = slug(ex.name);
    try {
      await prisma.exercise.upsert({
        where: { name: ex.name },
        update: {
          slug: exerciseSlug,
          category: ex.category,
          movementPattern: ex.movementPattern,
          skillLevel: ex.skillLevel,
          muscleGroups: j(ex.muscleGroups),
          secondaryMuscles: j(ex.secondaryMuscles),
          equipment: j(ex.equipment),
          avoidIfInjury: j(ex.avoidIfInjury),
          formTips: j(ex.formTips),
          commonMistakes: j(ex.commonMistakes),
          coachingCues: j(ex.coachingCues),
          alternatives: j(ex.alternatives),
          source: "custom",
        },
        create: {
          name: ex.name,
          slug: exerciseSlug,
          category: ex.category,
          movementPattern: ex.movementPattern,
          skillLevel: ex.skillLevel,
          muscleGroups: j(ex.muscleGroups),
          secondaryMuscles: j(ex.secondaryMuscles),
          equipment: j(ex.equipment),
          avoidIfInjury: j(ex.avoidIfInjury),
          formTips: j(ex.formTips),
          commonMistakes: j(ex.commonMistakes),
          coachingCues: j(ex.coachingCues),
          alternatives: j(ex.alternatives),
          source: "custom",
        },
      });
      created++;
    } catch (e) {
      console.warn(`  Skipped: ${ex.name}`, e);
      skipped++;
    }
  }

  console.log(`✅ Done! Created/updated: ${created}, Skipped: ${skipped}`);
  console.log(`📦 Total exercises in seed: ${EXERCISES.length}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
